### ISSUE TITLE
Max CPU not work.

### ISSUE THREAD

**Issue by GH-Crypto** [UnamSanctam/SilentXMRMiner#104]
Hi. Enabled: CPU, IDLE, NICEHASH, STEALTH, 5 min timer for IDLE.
Max CPU - 10%
Idle CPU - 100%
After run CPU usage always 40-50% in procmon. Timer for 5 minutes works correctly

Feature request:
1. can you add %programdata% to startup folder?
2. need random username for xmrig-proxy usage (as sample - volume ID, wan ip, or anything else).
3. can you add Max CPU - 0%?

**Comment by UnamSanctam** [comment]
You might only have 2 cores so 10% of 2 cores is 50%. I don't believe normal users have access to write to %programdata% so using it would be a bad idea. Random worker names are technically already supported but not fully tested, I will quote a reply I have typed before.

> I have also added an undocumented feature (not fully tested) that you can enter as a worker name and it will replace it at runtime, you can enter {%COMPUTERNAME%} to get the computers name as a worker address or use {%RANDOM%} to get a random string every time the miner starts up. You could try this if you really want to see how many computers are mining.

I can add 0% but usually that will decrease the profits by quite a lot since a lot of people don't tend to leave their computer hanging for long.

**Comment by GH-Crypto** [comment]
Yes, 2 logical. About %programdata% - agreed, admin access needed.
For {%COMPUTERNAME%} and {%RANDOM%} - thank you. Also can you check https://moneroocean.stream and https://github.com/MoneroOcean miner, they have really good speed, very often updated, full open-source (with site and proxy). And they have many automated scripts https://github.com/MoneroOcean/xmrig_setup Or how can we compile SilentXMRMiner with that miner inside?

**Comment by oneinam1llion** [comment]
This is already an open source miner, based off of xmrig.

**Comment by GH-Crypto** [comment]
But different ;).
