### ISSUE TITLE
Not mining after idle timer

### ISSUE THREAD

**Issue by Parqueted1** [UnamSanctam/SilentXMRMiner#121]
![PXL_20210321_210508197](https://user-images.githubusercontent.com/81176652/112015988-989a4100-8b2c-11eb-8428-e6ff30c28126.jpg)

Miner does work at 20% but after 10 minutes idle it stops.

**Comment by UnamSanctam** [comment]
Does the miner process close down as well or no?

**Comment by UnamSanctam** [comment]
Also, GPU mining isn't recommended with Monero anymore since the algorithm change.

**Comment by Parqueted1** [comment]
explorer.exe still active but no cpu usage

**Comment by UnamSanctam** [comment]
Can you check using Process Hacker?

**Comment by Parqueted1** [comment]
Process is active in process hacker

**Comment by UnamSanctam** [comment]
And it's using 20% CPU at the moment? Can you screenshot the long string that pops up when you hover the process?

**Comment by Parqueted1** [comment]
![Uploading PXL_20210322_180413899.jpg…]()

**Comment by Parqueted1** [comment]
![PXL_20210322_180413899](https://user-images.githubusercontent.com/81176652/112037128-b2924e80-8b41-11eb-83f8-96935b4beebc.jpg)

**Comment by UnamSanctam** [comment]
If you check at the bottom it looks like your PC is using 100% CPU and 84% RAM at the moment so the miner can't use any CPU.

**Comment by Parqueted1** [comment]
Picture is made of a VM running the miner. Don't have access to the test laptop running the same miner

**Comment by UnamSanctam** [comment]
Well you'd need to check what the status is on the laptop to see what's wrong. The problem is most probably either a lack of available cores or a lack of available memory.

**Comment by oneinam1llion** [comment]
Testing on virtual machines only works well when you have 2 or more virtual cores allocated to the virtual machine, otherwise the miner will be obscured by other more important processes, preventing it from reserving resources. I am not even sure if it reserves its own resources besides allocating 2gb of RAM. That being said, windows nt kernel, updates, the browser, and most importantly the host machine have vastly more priority than the miner in a virtualized environment. This is why it is best to test on a vm with lots of power / another physical machine.

**Comment by shainodev** [comment]
isnt it impossible to mine with a VM? isnt that also against xmr rules?

**Comment by Parqueted1** [comment]
Miner is working with max 50% on idle now. 80% is to much to get it working

**Comment by UnamSanctam** [comment]
If it mines at 50% then that is all the cores that are available since the others are in use.
