### ISSUE TITLE
Two Separate Icons

### ISSUE THREAD

**Issue by ThisIsAUser2** [UnamSanctam/SilentXMRMiner#13]
Hello, 

When I compile the miner it uses the same Icon for the executable and for the autostartup .exe, which lies for example in Appdata.

Where in the code I can make it that it uses separate Icons for payload and startup file.

Thank you in advance

**Comment by UnamSanctam** [comment]
The payload and startup applications are the same, the payload just copies itself to AppData so it's not really possible to only use an icon on one of them in a simple way.

**Comment by ThisIsAUser2** [comment]
> 
> 
> The payload and startup applications are the same, the payload just copies itself to AppData so it's not really possible to only use an icon on one of them in a simple way.

Would there be a way to let the executable automaticly change itself when it copies itself to the destined folder?

**Comment by UnamSanctam** [comment]
No easy way since currently this is what I do:
`Dim Client As Byte() = File.ReadAllBytes(Process.GetCurrentProcess.MainModule.FileName)
Drop.Write(Client, 0, Client.Length)`
So I just copy the entire running program.

To be able to change the icon when it copies you would either 1) Have to find a way to resource hack the application before or after it's been copied. 2) Include a second miner without an Icon embedded into the miner but that would essentially double the file size 3) Search the bytes for the icon and remove it. But none of them are really that easy or reliable without much testing.

**Comment by ThisIsAUser2** [comment]
Ok thank you
