### ISSUE TITLE
How do u change the donation address and I also want to change the donation to 10-20%%.

### ISSUE THREAD

**Issue by Anox208** [UnamSanctam/SilentXMRMiner#130]
I got my first payout I decided to use UnamSanctum ur address to donate to u to show my thanks. So pls give me ur address and i want to donate 10-20% of the hashrate to u. How do i do this in Visual studio 2019? Help me ty. Also all I wasn't using Nanopool so I got banned but I got my 1st payout so now i have to spread again lol. well i lost about .04 xmr for my 2nd payment

**Comment by golxd** [comment]
why banned?

**Comment by UnamSanctam** [comment]
Thank you, and yeah some pools will ban you so keep away from those if you are going to mine directly to them. You don't need to donate any hashrate but if you do earn enough to want to donate you can send some XMR to my donation address `8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N`

**Comment by golxd** [comment]
**UnamSanctam**, Can I still ask you a couple of questions about nanopool?) Only you help me)
**1.** How to log into your account to change the minimum output, where to get "password (email of your workers)" those support does not answer.
**2.** Is it better to mine on one specific Region? Or better mix eu.us.asia
**3.** What about bans? What pools are banned? for what?

**Comment by UnamSanctam** [comment]
1. You can start a miner on your own computer and mine 10 shares with the wallet address
 `YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL` 
for example: `8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.Worker/pass@fakeemail.com`
If you do mine at least 10 shares (so that the worker shows 10+ rating on nanopool) then you can go into settings and use the email as the password (in the example `pass@fakeemail.com`).

2. Technically it's better to mine to the region closest to the miner but since some users might be all over the world I usually just use one region.

3. Some pools ban you for having too many miners (usually over 100) without using something like xmrig-proxy, from what I know nanopool doesn't which is why I usually recommend it.

**Comment by golxd** [comment]
**understood**, thanks a lot. It's just that I will have more than 100 miners, so I'm worried)

**Comment by UnamSanctam** [comment]
Well if you mine on nanopool it thankfully shouldn't be a problem.
