### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by PXCorp** [UnamSanctam/SilentXMRMiner#144]
1) What pool you recommend to use?
2) Can i use MyMonero on android as a wallet?
3) Is it works on 32bit system?
 Thank you in advance :)

**Comment by UnamSanctam** [comment]
1. You can use any but if you plan to have many miners then you should use a pool which won't ban you for not using xmrig-proxy. I personally use nanopool for this, they don't really ban since they have a really high share difficulty (takes longer to mine but still gives same profit) so they can have more miners with less lag.
2. Yes you can use any Monero wallet.
3. No, it used to be but it has since moved away from 32-bit to only support 64-bit.

**Comment by PXCorp** [comment]
> 1. You can use any but if you plan to have many miners then you should use a pool which won't ban you for not using xmrig-proxy. I personally use nanopool for this, they don't really ban since they have a really high share difficulty (takes longer to mine but still gives same profit) so they can have more miners with less lag.
> 2. Yes you can use any Monero wallet.
> 3. No, it used to be but it has since moved away from 32-bit to only support 64-bit.

Thanks man :)
