### ISSUE TITLE
Can traffic be split?

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#145]
For example two connections: 50% pool wallet1 and 50% pool wallet2

**Comment by timboft** [comment]
xmrig proxy

**Comment by UnamSanctam** [comment]
Some pools like MoneroOcean also supports this I believe.by adding %percent2%xmr_wallet_address2 after the wallet address.

**Comment by Toxenskiy** [comment]
а разве в xmrig можно разбивать траффиик?

**Comment by Toxenskiy** [comment]
But through the miner itself, can you somehow do it?

**Comment by UnamSanctam** [comment]
No, since the only real way to do that is to change pool/wallet address every nth minute (depending on %) but that would be quite inefficient (or mine to separate pools with different cores but that would be way too advanced and clunky). So because of how mining works it will always be better to do it on either the pool side or on a proxy.

**Comment by Toxenskiy** [comment]
ok, and how to do it through xmrig proxy

**Comment by UnamSanctam** [comment]
Well from what I know you'd have to do it quite advanced like having a script running that restarts it with a new pool every x amount of minutes, or you can just mine to MoneroOcean, although using a proxy to do that is better than mining directly to it.
