### ISSUE TITLE
Idle

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentXMRMiner#154]
idle mining works for both cpu and gpu?

**Comment by UnamSanctam** [comment]
Yes, although GPU mining isn't very profitable (but still possible) for Monero anymore since the algorithm switch, things like Ethereum are much more profitable to mine with GPU, https://github.com/UnamSanctam/SilentETHMiner.

**Comment by UnamSanctam** [comment]
ETH is more profitable per computer but requires a GPU with over 4GB VRAM and new enough drivers to support CUDA 11 while XMR is less profitable per computer but has nearly no requirements to run so it's easier to spread to more computers.

GPU mining relies on the memory and memory clock to run so no core clock (GPU Usage) should be used. When it's mining at full speed it should be using around 0% GPU load but at full memory clock.

Since both my miners are compatible with each other you can run both the XMR and ETH miners at the same time without any issues.

**Comment by golxd** [comment]
Yes, you can use it together, but then you need a person to run 2 exe instead of 1, if only they could be combined into one file)
I like how SilentETHMiner mines, but if a person conditionally plays games with a miner, he will have terrible lag? And he will most likely do something about it.

**Comment by UnamSanctam** [comment]
Well you can use a file binder to combine them (there are many here on GitHub). And the miner will decrease its memory clock usage while something else is using it, the only thing which could clash is if they play a game which tries to allocate the whole VRAM.

**Comment by golxd** [comment]
Well, thanks, I'll try to combine it, I hope this will not negatively affect the work of miners)

**Comment by golxd** [comment]
are the detection rates of different antiviruses the same on XMR and ETH?

**Comment by UnamSanctam** [comment]
Should be since the injectors are mostly the same code wise. The actual miners don't really get detected.
