### ISSUE TITLE
Random Worker name and cryptor

### ISSUE THREAD

**Issue by PXCorp** [UnamSanctam/SilentXMRMiner#163]
1) How to make random worker name?
2) What is the best cryptor?

**Comment by UnamSanctam** [comment]
1. You can use either {%RANDOM%} to get a fully random name or {%COMPUTERNAME%} to get the computer name. Keep in mind though that most pools only allow between 50-100 worker names total.
2. There isn't really a best one, there are many, many ones available, personally I usually try with https://github.com/mkaring/ConfuserEx but since a lot of people use it it usually gets detected after while.
