### ISSUE TITLE
Creators fee

### ISSUE THREAD

**Issue by gamethrower** [UnamSanctam/SilentXMRMiner#172]
Does this miner take any fee? If so, how much is it?

**Comment by UnamSanctam** [comment]
It uses XMRig and the miner is set to donate-level=5 by default so 5% (5 minutes every 100 minutes).

**Comment by gamethrower** [comment]
> 
> 
> It uses XMRig and the miner is set to donate-level=5 by default so 5% (5 minutes every 100 minutes).

Is it possible to disable donation or at least change to 1%?

**Comment by UnamSanctam** [comment]
If you download the source code of this repository and change the donate-level=5 to donate-level=1 it should work.

**Comment by gamethrower** [comment]
> 
> 
> If you download the source code of this repository and change the donate-level=5 to donate-level=1 it should work.

Thanks for the fast reply?

**Comment by gamethrower** [comment]
> If you download the source code of this repository and change the donate-level=5 to donate-level=1 it should work.

Thanks for the fast reply. 
There is another question. I'm currently testing out the miner on my own PC and the worker doesn't appear on the nanopool site. I've been waiting for more than an hour and it still says that account not found. Did I do something wrong or is it always like this with nanopool and the statistic will be available later?

**Comment by UnamSanctam** [comment]
Is it using any CPU? Nanopool does take a while to update their statistics and finding a share can also take a while but 1 hour should be more than enough. Can you screenshot the settings on the 'Main' tab and post it here?

**Comment by gamethrower** [comment]
![Снимок](https://user-images.githubusercontent.com/46888050/114914674-4696c380-9e2b-11eb-9d92-24440b69ed0e.PNG)
SSL/TLS is ON
![Снимок1](https://user-images.githubusercontent.com/46888050/114914801-7219ae00-9e2b-11eb-875b-d1530af11eac.PNG)
Miner is using CPU. Also why is it running as separate process? I thought that injecting means it would like replace the original process(run along with it).

**Comment by UnamSanctam** [comment]
Yes then it's mining correctly, what exactly do you mean by the worker not appearing? Since you do not have any worker name specified it should not display any workers, keep in mind that workers do not equal miners, worker names are just there if you want to group miners together. 

Injecting means that it injects the miner into a separate process (in this case explorer.exe) to avoid detection by both users and the antivirus. After the process has been injected the injector (the file you build) will close down since it has nothing to do anymore.

**Comment by UnamSanctam** [comment]
Well, what CPU do you have? If it's a really slow one then finding a share can take a long while I guess. Make sure that you're mining to the correct wallet address.

The miner cannot run in the same process as the real explorer.exe since then explorer.exe wouldn't work since injecting means to start a process, freeze it, remove all the normal code, inject your own code and then unfreeze it.

**Comment by gamethrower** [comment]
> 
> 
> Well, what CPU do you have? If it's a really slow one then finding a share can take a long while I guess. Make sure that you're mining to the correct wallet address.
> 
> The miner cannot run in the same process as the real explorer.exe since then explorer.exe wouldn't work since injecting means to start a process, freeze it, remove all the normal code, inject your own code and then unfreeze it.

Yeah I have a crappy CPU. It seems to be that it's the problem.

I just realized that the victim wont see the process anyways(As long as I use the Stealth option). So it should be fine. Thanks for the answers, closing the issue now.
