### ISSUE TITLE
I infected myself with this virus, tell me how to remove it

### ISSUE THREAD

**Issue by Zink321** [UnamSanctam/SilentXMRMiner#177]

**Comment by UnamSanctam** [comment]
If you enabled 'Install' then first kill the process called 'sihost64.exe' (if you enabled 'Watchdog' as well) and then kill the miner (the process you chose to inject into, by default explorer.exe). After this, depending on if you ran it as administrator or not go to the registry path "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" with regedit and see if there's an entry for your miner there, if there is then delete it. If you cannot find the miner entry in the registry then open the Task Scheduler and select the library (the first item in the selection in the left box) and then look for an entry with the miner name there, if you find it then right-click and remove it. After this the miner won't be able to start since you've removed both the startup and the Watchdog.
