### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by WhoR3born** [UnamSanctam/SilentXMRMiner#183]
hi i tried to inject different sources but not working?
im not sure maybe doesnt get job but how can i be sure?
using supportxmr as pool.
tried different ports too.
(testing on windows server 2016 rdp)

(very first start wiith using %20 cpu (i set it to %10) and 2gb ram then ~10 seconds later using %0 cpu and 2gb ram)

i used with debug mod too but didnt get any error.

**Comment by UnamSanctam** [comment]
Did you enable 'Stealth'?

**Comment by WhoR3born** [comment]
> 
> 
> Did you enable 'Stealth'?

yes i did

**Comment by UnamSanctam** [comment]
'Stealth' will pause the miner while Task Manager, Process Hacker or Process Explorer is open so that would be why it says that it uses 0% CPU if you have any of them open. The miner will use the percentage of the CPU cores available so if you choose 10% but your computer only has 2 cores then it will use 1 core (the minimum) which would be 50%.

Yes they need .NET Framework but most people have that since it automatically comes with Windows and get automatically updated with Windows Update.

**Comment by alix1011** [comment]
Hi, I have the same problem, I used different ports and turned off stealth, but after running Miner, it does not use the cpu.
