### ISSUE TITLE
Donate level

### ISSUE THREAD

**Issue by gamethrower** [UnamSanctam/SilentXMRMiner#185]
So I compiled the xmrig with default and minimum donate level 0. 
I replaced your xmrig in miner project with this one. Where exactly should I change the donate level in your code? I found 2 parts with "--donate-1" string. Should I just change it to "--donate-0"?

**Comment by UnamSanctam** [comment]
Change it on line 90 in Form1.vb to --donate-level=0

Keep in mind that since you've replaced the custom XMRig the 'Stealth' and 'Idle Mining' options won't work (since they don't exist in the normal miner). It will also flash a CMD window quickly when starting the miner (due to the normal XMRig --background behavior).

**Comment by gamethrower** [comment]
> 
> 
> Change it on line 90 in Form1.vb to --donate-level=0
> 
> Keep in mind that since you've replaced the custom XMRig the 'Stealth' and 'Idle Mining' options won't work (since they don't exist in the normal miner). It will also flash a CMD window quickly when starting the miner (due to the normal XMRig --background behavior).

Damn, Is there a way to fix this?

**Comment by UnamSanctam** [comment]
No not really, I mean setting it to --donate-level=1 will only mine to the dev address for 1 minute every 100 minutes so it isn't that much of a difference really.

**Comment by gamethrower** [comment]
> 
> 
> No not really, I mean setting it to --donate-level=1 will only mine to the dev address for 1 minute every 100 minutes so it isn't that much of a difference really.

I don't get it. Did you somehow modify and compile the xmrig miner so it's more silent? (Like it doesn't flash a cmd)

I'm afraid that this will affect the progress. Since my target is a shit ton of crappy pc switching to other pool even if it's just a minute make me lose a block or something. (I'm not sure how all of this works) 
Also I'm a greedy fuck :/

**Comment by UnamSanctam** [comment]
Switching the pools won't really affect anything since mining is luck based and you have the same chance of finding anything no matter how long you've mined. Keep in mind that that is for solo mining only, for pool mining it won't matter at all if you switch pools since you don't get anything special for finding a block either way. I have compiled the XMRig with the Windows subsystem instead of the console and then added a start entry so that no CMD window flashed before it goes into the background mode.

**Comment by gamethrower** [comment]
Another question. What should I crypt? Only watchdog or both watchdog and the final exe?

**Comment by UnamSanctam** [comment]
Both preferably, you can use anything, preferably a .NET Obfuscator or something similar. I don't know which crypter/obfuscator you're going to use but I've recently found a crack for .NET Reactor which works very well from my tests, I will quote what I've written before here in case you don't have any crypter in mind at the moment.

>You could also use the much better .NET Reactor instead since I've found a crack for the current version of it. If you want to use that instead then download https://anonfiles.com/J1wbgdsfuf/ and extract it. Then run the setup, after that's done go to the folder you installed it to and drag the .exe in the Crack folder into the installed folder and replace the normal .exe and it should work. Keep in mind that I got the crack online so it could be infected with malware of something like it so run it in a VM or something to be safe if you can (that's what I do at least).

>If you use .NET Reactor then try these settings first:
![.NET Reactor Settings](https://i.imgur.com/WzVTID8.png)
You can also enable things like 'Code Virtualization' or the other settings if it does show up as detected to reduce it.

**Comment by gamethrower** [comment]
Thanks for your answers.
