### ISSUE TITLE
obf

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentXMRMiner#193]
Tell me, I'm testing obfuscator, which site is better to use for checking for viruses. Maybe eat something other than virustotal and antiscan

**Comment by UnamSanctam** [comment]
Well https://antiscan.me/ works but only for a few scans every day. It's hard to find antivirus analysis sites that don't distribute the results (like virustotal, you don't want a site where they distribute it since that will cause your file to get detected).

**Comment by golxd** [comment]
I do not understand what to orientate on, antiscan shows that there are no viruses, but my windows defender is blocking the file.

**Comment by UnamSanctam** [comment]
What does it detect it as? Can you open Windows Defender and screenshot the detection?

**Comment by golxd** [comment]
this? 
![image](https://user-images.githubusercontent.com/81568432/115663622-78d38400-a349-11eb-87c4-0ecad6a39533.png)

**Comment by UnamSanctam** [comment]
Yes exactly, that is a code signature detection that your computer found but all Windows Defender detect things differently so some will detect it as that, some as something else and some not at all. This is usually why we obfuscate the program so that the code signatures become different. (I use the term code signature loosely here)

**Comment by golxd** [comment]
so, I tried about 10-15 combinations in .NET Reactor, they all detect Defender on my computer, but not the fact that on other computers it will be found. Then ignore windows defender and just look at the antiscan site, right?

**Comment by UnamSanctam** [comment]
Yes you can do that, do you obfuscate it with .NET Reactor inside a VM and then copy it to your computer and then test it with WD? Or do you just obfuscate it directly on your computer and test it some other way with WD? What specifically is your workflow?

**Comment by golxd** [comment]
I didn't use a VM, I have a laptop for tests, so I did everything on it, and tested WD on it too. This is bad?

**Comment by UnamSanctam** [comment]
No no, it's fine. I just wanted to know your workflow. You should be able to use that file if antiscan says it's undetected. You could also try this project file https://anonfiles.com/P303z9s2ub/Unam_zip that I put together quickly that at least works for me. (Press 'Open Project' in the left side)

**Comment by golxd** [comment]
something new)
![image](https://user-images.githubusercontent.com/81568432/115667173-33fe1c00-a34e-11eb-8286-08724c7c9f52.png)

**Comment by UnamSanctam** [comment]
Ah yeah that's also one, hmm. Have you tried with things like Code Virtualization and those kinds of options. Since antivirus companies don't want their detections to help the makers avoid them they tend to be loosely defined on purpose so the solution is usually just to test more options. But if you feel confident after it hasn't shown any results in antiscan then it should be fine or at least better than if you never obfuscated at all.

**Comment by golxd** [comment]
virtualization tried it too. Yes, I'll just look at antiscan, I agree with you, it will be better than nothing. enough tests. thanks for always helping
