### ISSUE TITLE
what the heck?

### ISSUE THREAD

**Issue by LYZEN77** [UnamSanctam/SilentXMRMiner#195]
![image](https://user-images.githubusercontent.com/51676266/115744937-ac3efe80-a39b-11eb-8988-0660d75bca19.png)
why would it even need the hosts, is this a part of the plan or we missin' something...

**Comment by UnamSanctam** [comment]
NYAN-CAT (who made the original Lime-Miner) added that a long while ago here: https://github.com/UnamSanctam/SilentXMRMiner/blob/f4d62ef949bde27119df1ede191c38ae954c1524/SilentXMRMiner/Form1.vb#L33 I'm pretty sure he added it since he was tired of all the people uploading the miner to VirusTotal, since if you do the miner becomes detected since they are a distribute site.

**Comment by gamethrower** [comment]
> 
> 
> Yes they all get sent for deeper analysis, normally they won't do that for the files on your computer but since only single files that people are suspicious of gets uploaded to virus total they can afford to do more tests. Also, let's say that only one antivirus detects the file then it will get sent to all the other antiviruses saying that one other has detected that and because of that they will often flag the file as a virus as well. It also allows them to improve their detection rates by seeing what all the others are detecting it as.

Do they share data between them? I mean if  an AV on your PC will detect my malware and save its fingerprint will it later report it to other AVs?

**Comment by UnamSanctam** [comment]
Yes in some capacity but they will always do that on sites like Virustotal.

**Comment by gamethrower** [comment]
> 
> 
> Yes in some capacity but they will always do that on sites like Virustotal.

Also, on the stage of static code analyze does AV see comments and variable/function names in C#? What about C/C++?

**Comment by UnamSanctam** [comment]
For C# you can't see comments since they get removed but variable and function names remain. In native C/C++ then no, you can't really see anything there.

**Comment by gamethrower** [comment]
> 
> 
> For C# you can't see comments since they get removed but variable and function names remain. In native C/C++ then no, you can't really see anything there.

So C/C++ gets converted to assembly code cleaning up all the names and comments? Is there any way to access the original code. Like get the assembly from memory and automatically convert it to C?

**Comment by UnamSanctam** [comment]
Yeah it depends on the compiler but usually the code gets converted into assembly code which then gets converted into "machine code" which the linker then manages together. Once C/C++ has been compiled that way there is no real way to convert it back to C/C++ easily.

**Comment by MarkSkith** [comment]
Yes this is true, but you can still notice certain flags in assembly code through reading memory. Even though strings aren't easily readable while c/c++ is compiled, they are still present. Therefore you can use software, such as cheat engine, to debug and get all strings referenced by the program in runtime. This is how game hacks work, can be easily used to crack software too. Any software that has a void for checking a password then a void for starting the password protected void can be hacked, for instance, you can just force the void that checks passwords to redirect to the "correct" void, instead of the "password failed" void. Pretty simple stuff, see it in practice all the time, especially with bad code that doesn't have fail safe checks.

**Comment by UnamSanctam** [comment]
Yes of course but turning it back into easily readable and usable C/C++ code would take a lot of work.

**Comment by MarkSkith** [comment]
Yeah, I don't event think its possible.
