### ISSUE TITLE
How to set

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#197]
I have a question for you, how to cancel this in the software
![CM_XVC2$2%9_`V`SIW70X4M](https://user-images.githubusercontent.com/73113267/115840833-b110ba80-a44e-11eb-8438-a57bce19cc03.png)

**Comment by zoubaba1997** [comment]
This is not the case with the software you made, but the software I wrote will be like this, what should I do?

**Comment by UnamSanctam** [comment]
That is SmartScreen which some computer have enabled, it will always show that for programs that have a low reputation (not many have run it) or don't have a certificate by Microsoft. https://docs.microsoft.com/da-dk/windows/win32/win_cert/windows-certification-portal?redirectedfrom=MSDN. Does you program have a GUI? My miner usually doesn't show the SmartScreen because it doesn't have a GUI but if yours does it will shot that and there isn't much you can do about it without making your program trusted with a certificate.

**Comment by zoubaba1997** [comment]
There is no GUI, but it is still like this. I wrote a batch process to add win10 exclusions and download miners from the server.

**Comment by zoubaba1997** [comment]
I converted this batch into an exe file

**Comment by UnamSanctam** [comment]
Yeah and that .exe triggers the SmartScreen with something it does. If you're using some converter then try using another one and see if that triggers it as well.

**Comment by zoubaba1997** [comment]
Thanks for your quick answer

**Comment by zoubaba1997** [comment]
I have tried many tools like this, usually the victim will not continue to run the miner when seeing this situation

**Comment by zoubaba1997** [comment]
Even if it is not converted into an exe file, it is just a bat file.

**Comment by UnamSanctam** [comment]
Yeah, does it show up when running the .bat file as well? It shouldn't but I'm just asking.

**Comment by zoubaba1997** [comment]
Yes, when the .bat file is running, it will also be displayed, I have tested it on many computers

**Comment by UnamSanctam** [comment]
Hmm, I believe it does that since the file comes from another computer usually.

**Comment by zoubaba1997** [comment]
Is there any way to solve it? In addition to adding a digital signature method

**Comment by UnamSanctam** [comment]
It should naturally go away if enough people download and run it because the file's reputation will go up.

**Comment by zoubaba1997** [comment]
How much does it need? My current downloads are about 6000

**Comment by zoubaba1997** [comment]
How many downloads are needed, I currently have about 6000 downloads

**Comment by UnamSanctam** [comment]
Microsoft is the one that decides that and has never told anyone since they don't want it abused. You can read this Stackoverflow answer https://stackoverflow.com/questions/33414291/how-can-i-stop-my-installer-from-triggering-windows-10s-this-app-has-been-bloc/33505832#33505832 which is correct in what it says.

**Comment by zoubaba1997** [comment]
Ok, thank you
