### ISSUE TITLE
Selfdestruct on open

### ISSUE THREAD

**Issue by ThisIsAUser2** [UnamSanctam/SilentXMRMiner#20]
Is there a way to remove the file (not from the autostart folder) if you open on it?
I am not good at VB, but I think you could do an If-Statement to check if the file is in the autostart folder. And if it is not it would delete itself (assuming a user has clicked on it)

**Comment by UnamSanctam** [comment]
Is there a need to? If you have the Install option enabled it will copy itself to another folder and add itself to the registry.

**Comment by ThisIsAUser2** [comment]
Hello, 
yes I need it in to self destruct to be more stealthy. I would be greatful if you could help me. Thank you

**Comment by UnamSanctam** [comment]
Since a program cannot be deleted when it's running you would either have to start a delayed CMD command that removes the file after it's done running. Another way is to add into the code that after it has copied itself when installing it has to start the copied program with a command line argument containing the path of itself and then when the program starts with that string it removes the file in that path. Both options aren't that easy or reliable to do so there isn't really an easily understandable way that I can help you unless you have some proficiency with programming.
