### ISSUE TITLE
Miner options

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentXMRMiner#207]
Hi my friend, write a program, use it when the miner ran on the wrong system or we wanted to remove the miner on the system.  In the new updates, Im waiting for the excellent miner options،New ideas can be amazing.

**Comment by UnamSanctam** [comment]
If I understand you correctly then you want a program to remove the miner? This program would have to be built alongside the miner when you build it in the builder since otherwise it would never know the miners 'Install' options but it's technically possible to do. Would probably add it as an 'Advanced Option' then.

**Comment by alix1011** [comment]
Yes tnx

**Comment by alix1011** [comment]
There is a problem, I am running Miner on one user from the server, but if other users notice and close the Miner user, Miner will no longer run on other users, in future updates, Miner will be on all users.  .

**Comment by UnamSanctam** [comment]
Since Windows require administrator permissions to run on other users you have to start the miner with administrator privileges, I have already added the functionality that so that when run as admin it will add the task into Task Scheduler for all users. So if you run the miner as administrator it should work.

**Comment by alix1011** [comment]
Yes, with administrator access, I run Miner, but it does not run on other users.  I check again, maybe I'm wrong.

**Comment by UnamSanctam** [comment]
Yeah, maybe it's set to run for the current user, not sure since I didn't write the schtask command to add it but I'll check it and change it if it's wrong in the next version.

**Comment by alix1011** [comment]
Thanks my friend for the great and fast support, I have a problem or a new idea, let me know.
