### ISSUE TITLE
Custom Miners / Algos

### ISSUE THREAD

**Issue by lonewolfman** [UnamSanctam/SilentXMRMiner#211]
First off, just wanted to thank you for continuing NYAN-CAT's legendary work. 

Hypothetically, if I swap out xmrig with another CPU-based miner, would the builder successfully compile? (Assuming that the miner parameters are the same -- if not, some simple changes in VS to fit the new miner/algo).

**Comment by UnamSanctam** [comment]
Yes that would work, the program can technically inject any native (C/C++ or whatever) program with command arguments since it's really just a specialized crypter. You should also replace the Watchdog.cs and Program.cs 'RCheckProc' 'contains' variables so that it looks for a part of the command line that the new miner would have. I am not sure whether the injector is set to create a visible window or not though since I've removed the window of the miner in the code myself so I've never bothered to check.

**Comment by lonewolfman** [comment]
Cool, I'll play around with it tonight. If you're up for it, I think a next cool project would be SilentCustomMiner ;) I've been playing with CPU-only PoW coins, some coins are far more profitable than XMR.

**Comment by UnamSanctam** [comment]
Yeah, keep in mind that XMRig also supports all these algorithms https://xmrig.com/docs/algorithms

**Comment by lonewolfman** [comment]
I'm aware 😉 But CN-variants and RandomX aren't what I'm looking for. YesPoWer/Yescrypt coins are giving me consistently higher returns. If you haven't realized by now, I like going after small market cap coins. No risk no gain! Hahah.

**Comment by UnamSanctam** [comment]
Haha, just tell me if there is something that doesn't work for you and I'll try and fix it.

**Comment by lonewolfman** [comment]
Quick question, currently on the road and haven't had much time to skim through the source -- how is the CPU usage during idle/normal changed? Through xmrig's config parameters, or the build itself?

**Comment by UnamSanctam** [comment]
I've coded it myself into the XMRig and it then uses the `--unam-idle-cpu`, etc. XMRig config parameters. Personally I find CPU % (`max-cpu-threads-hint`) better since it's more dynamic then and that brings more profit on really good CPUs with no real penalties for anything else.

**Comment by alix1011** [comment]
My friend, do you know another digital currency for mining that is more profitable ??  Or you want to change the extraction algorithm to make more profit؟??.
