### ISSUE TITLE
Can a miner cleverly reduce cpu load when the end user needs processor resources, for example, for a game?

### ISSUE THREAD

**Issue by bakaba277** [UnamSanctam/SilentXMRMiner#231]

**Comment by bakaba277** [comment]
Сan a miner cleverly reduce cpu load when the end user needs processor resources, for example, for a game?

*fix*

**Comment by UnamSanctam** [comment]
It should already do that, it should yield CPU to any other program that needs it since the miner should have less priority. You can also add `--cpu-priority=0` (or any other number, it sets process priority (0 idle, 2 normal to 5 highest) in the 'Advanced Parameters' field if you want to control the setting yourself.

**Comment by bakaba277** [comment]
understood, thank you
