### ISSUE TITLE
I hope you realize in the next version:

### ISSUE THREAD

**Issue by bakaba277** [UnamSanctam/SilentXMRMiner#237]
- random name of the worker via gui
- gluing of miner with other programs through gui

Well, in general, what plans/ideas
?

**Comment by UnamSanctam** [comment]
For the random worker name you can just enter {%RANDOM%}  or {%COMPUTERNAME%} as the worker name and it will either randomize it or use the computer name as the worker name.

And for the second point, I'm planning on making a separate file binder since including it into the miner isn't the best solution.

These are the current things coming in the next version that I can think of:

- Update XMRig to 6.12.1
- Remote Configuration from pastebin or other similar sources
- Auto-create Uninstaller option
- Rework whole code for detection bypasses
- Windows Defender "Killer"
- Fix old limitations
- Other fixes

**Comment by bakaba277** [comment]
>For the random worker name you can just enter {%RANDOM%} or {%COMPUTERNAME%} as the worker name
I know. I want (and I'm not alone) to do this with one button

>Remote Configuration from pastebin or other similar sources
why? miner will cease to be open sourse? what for?

when is the release planned?

**Comment by UnamSanctam** [comment]
>I know. I want (and I'm not alone) to do this with one button

All pools input their worker names differently so having a single button do that would be impossible.

>why? miner will cease to be open sourse? what for?

No, the remote configuration means that you can enter all the pool settings on something like pastebin and then enter the pastebin link into the miner and it will get those settings from that URL every time the miner starts up. This means that you can change the pool settings without having to rebuild the miner.

>when is the release planned?

Release is planned either today or tomorrow but it will probably be tomorrow since I have to update the wiki and write guides for how to do everything.

**Comment by bakaba277** [comment]
>No, the remote configuration means that you can enter all the pool settings on something like pastebin and then enter the pastebin link into the miner and it will get those settings from that URL every time the miner starts up. This means that you can change the pool settings without having to rebuild the miner.

That is, pastebin is not code hosting? and miner will continue to be open sources?

>Release is planned either today or tomorrow but it will probably be tomorrow since I have to update the wiki and write guides for how to do everything.

i'll be waiting :)

**Comment by UnamSanctam** [comment]
>That is, pastebin is not code hosting? and miner will continue to be open sources?

Yes it will still be open source, pastebin is just somewhere where you upload text which in this case would be the pool settings (pool address, wallet address etc) that your miner should get whenever it starts up.

**Comment by bakaba277** [comment]
everything, I finally understood :)

**Comment by bakaba277** [comment]
I do not want to create a new thread, I will ask here

If I translate the program into Russian, will you add the translation?
If yes, point to the files where the source texts are stored in English

**Comment by UnamSanctam** [comment]
Well you could translate it but there is a lot of text inside the program and I all the text is inside all the files as normal and don't exist as a separate. I would also have to create some sort of function that loads all the text dynamically depending on the language chosen.

**Comment by bakaba277** [comment]
that is, gui text elements are scattered among different files?

**Comment by UnamSanctam** [comment]
Most GUI text is inside the https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Form1.Designer.vb and https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Advanced.Designer.vb files but also exist in some other places.

**Comment by bakaba277** [comment]
and another
how does visual basic work with characters that are not included in ascll?
maybe I should not climb into the program code itself, but write the translations of certain words into a separate file?

**Comment by UnamSanctam** [comment]
It should work fine with non-ASCII characters but you can also write it into a separate file which I would then use when implementing a localization system.

**Comment by bakaba277** [comment]
>but you can also write it into a separate file
this. 
naturally, in addition to translation, I will leave the line number from which the source text was taken, and the source text itself, so that it is more convenient for you to work with it

I will begin work, perhaps, when the new version of the miner is released :)
