### ISSUE TITLE
my money is running low

### ISSUE THREAD

**Issue by WexisQ** [UnamSanctam/SilentXMRMiner#246]
What is the reason why my money suddenly fell out

**Comment by UnamSanctam** [comment]
What? Could you retranslate that?

**Comment by WexisQ** [comment]
my money was 6.17 dollars, 30 mins later it's been 6 dollars

**Comment by UnamSanctam** [comment]
Because the prices of the cryptocurrencies change?

**Comment by UnamSanctam** [comment]
https://coinmarketcap.com/currencies/monero/

**Comment by WexisQ** [comment]
I'm mining xmr using the binance wallet. would it be a problem?

**Comment by UnamSanctam** [comment]
Technically not a problem on most pools though I would never recommend it due to the high fees and security risks. Setting up your own wallet takes like 20 seconds anyways so there's not much reason to use an exchange wallet.

**Comment by WexisQ** [comment]
Can I change the address I have mining now?  what do you mean by high fee and security risk.

**Comment by UnamSanctam** [comment]
I'm guessing you're referring to the Binance exchange wallet, they have their own high withdrawal fee + a high transaction fee, the wallet address can sometimes change as well since it's not supposed to be used as a real wallet. The wallet is hosted on their servers, they own the private keys and you have no control over what happens to it. You would have to create new miners with a new real wallet address and spread that instead.

The most common wallet is the one created by the Monero team and can be found here: https://www.getmonero.org/downloads/ (the GUI wallet)

**Comment by illegaler** [comment]
> I'm guessing you're referring to the Binance exchange wallet, they have their own high withdrawal fee + a high transaction fee, the wallet address can sometimes change as well since it's not supposed to be used as a real wallet. The wallet is hosted on their servers, they own the private keys and you have no control over what happens to it. You would have to create new miners with a new real wallet address and spread that instead.
> 
> The most common wallet is the one created by the Monero team and can be found here: https://www.getmonero.org/downloads/ (the GUI wallet)

Which wallet do you recommend for ETH?

**Comment by UnamSanctam** [comment]
I use Exodus at the moment.

**Comment by illegaler** [comment]
Thanks for the very quick reply lol
I'll try to use that wallet.
