### ISSUE TITLE
do i have to install nanopool for it to work

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#248]
do i have to install nanopool and run it, or do i just copy paste this    xmr-us-east1.nanopool.org:14433
and enter my personal bitcoin address
im new to this srry    i also have electrum as my bitcoin wallet, will that work for this?

**Comment by UnamSanctam** [comment]
Just enter xmr-us-east1.nanopool.org:14433 as the pool address (and enable 'SSL/TLS' in the mining settings since you use the SSL port 14433) and then enter your Monero wallet address in the 'Wallet Addres/User' field. I also have more in-depth information on my wiki: https://github.com/UnamSanctam/SilentXMRMiner/wiki

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Just enter xmr-us-east1.nanopool.org:14433 as the pool address (and enable 'SSL/TLS' in the mining settings since you use the SSL port 14433) and then enter your Monero wallet address in the 'Wallet Addres/User' field. I also have more in-depth information on my wiki: https://github.com/UnamSanctam/SilentXMRMiner/wiki

i have electrum as a wallet, i dont know if that will work the same way, do i have to setup from getmonroe

**Comment by UnamSanctam** [comment]
You need a Monero wallet for it, Electrum is a Bitcoin wallet and only works with Bitcoin, nothing else. You can download the GUI wallet at https://www.getmonero.org/downloads/ and just use simple mode to create one easily.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> You need a Monero wallet for it, Electrum is a Bitcoin wallet and only works with Bitcoin, nothing else. You can download the GUI wallet at https://www.getmonero.org/downloads/ and just use simple mode to create one easily.

do i have to install nanopool as well

**Comment by UnamSanctam** [comment]
There's no such thing, Nanopool is just a pool that you mine to. Just point the miner to Nanopool and when started the miner will mine until you reach the minimum payout and then they will send the amount you've mined to the wallet address you're mining to.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> There's no such thing, Nanopool is just a pool that you mine to. Just point the miner to Nanopool and when started the miner will mine until you reach the minimum payout and then they will send the amount you've mined to the wallet address you're mining to.

so im supposed to download the miner?   i also dont see any mining tab on the nanopool website so i dont know how to enable ssl, i also dont know how to set my bitcoin wallet

**Comment by UnamSanctam** [comment]
No you download my miner https://github.com/UnamSanctam/SilentXMRMiner/releases and enter the nanopool pool address and your Monero wallet address on the first tab of it. 

A pool is just a combined effort to mine blocks, you can technically mine blocks yourself without a pool but you would need a lot of miner/hashrate which is why we usually combine hashrates in a pool and get payed by the amount of effort put in by your miner relative to others when mining a block.

And to get a Monero wallet just download the GUI wallet here https://www.getmonero.org/downloads/ and it will work as any other cryptocurrency wallet.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> No, you download my miner https://github.com/UnamSanctam/SilentXMRMiner/releases and enter the nanopool pool address and your Monero wallet address on the first tab of it.
> 
> A pool is just a combined effort to mine blocks, you can technically mine blocks yourself without a pool but you would need a lot of miner/hashrate which is why we usually combine hashrates in a pool and get payed by the amount of effort put in by your miner relative to others when mining a block.
> 
> And to get a Monero wallet just download the GUI wallet here https://www.getmonero.org/downloads/ and it will work as any other cryptocurrency wallet.

do i put my password for the gui in

**Comment by UnamSanctam** [comment]
No, the password is for some pools that use it (which nanopool does not). Never share your GUI password or mnemonic seed or spend keys with anyone. The GUI wallet is made by the Monero team (who made Monero) and is as safe as it can be but you would have to ask them.
