### ISSUE TITLE
obfustication and suddnly stoping

### ISSUE THREAD

**Issue by silentminer22** [UnamSanctam/SilentXMRMiner#264]
helllo guyz first of all thanks for the amaizing tool having a ffew problems in my lab like there is a point were the miner just dont work or suddenly stop is it because of installing it many times or is there any posibilitiies that obfustication can curse the program to break?

and also wanted to implement a persistance mechanisim to autostart the file itsself like i think it might be easy for av evasion
like something that can run the fileless file in its location in the registry .or if at any point u guyz reach 0detection by Av coz my best was 2-3 adware giving me the most trouble off-coz

**Comment by UnamSanctam** [comment]
Well if you send the settings you used here I can see if any of them are wrong or anything. And it depends on what obfuscations you do but if 99% of them will work, you can also read more here: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

The miner will already autostart with Windows if you enable 'Install' but reaching 0 detections is nearly impossible since some antiviruses detect nearly all uncommonly run files as malware. If only 2-3 antiviruses detect it then that is already really good, most other programs usually have around 10-15 detections as a standard.

**Comment by dyachenkomark** [comment]
I have continued to test silentXMR on Win7 SP1 and have noticed unstable work throughout the night. Every half an our it restart, do you think it because of windows antivirus? I will attach some photo to see situation. ![image](https://user-images.githubusercontent.com/82396918/118347114-5e0bbe00-b549-11eb-9955-7079980e3d4c.jpeg)![image](https://user-images.githubusercontent.com/82396918/118347123-64019f00-b549-11eb-9493-342a6b21514d.jpeg)![image](https://user-images.githubusercontent.com/82396918/118347125-682dbc80-b549-11eb-8072-b309c52ef1c5.jpeg)

**Comment by UnamSanctam** [comment]
No that's just normal, check https://help.nanopool.org/article/62-faq#6.-hashrate specifically point 3.
