### ISSUE TITLE
Unrelated question

### ISSUE THREAD

**Issue by kaance** [UnamSanctam/SilentXMRMiner#274]
Hi bro do you know can we inject exe to jpg or pdf or office documents

**Comment by UnamSanctam** [comment]
Not jpg but for pdf or office documents you would have to find some exploit that allows code to be run when opening them.

**Comment by kaance** [comment]
For example can i inject my miner to a office document? do you know any github page for that? Thank you for your help

**Comment by UnamSanctam** [comment]
Not in an easy way, most of these exploits also get fixed pretty fast. So if an exploit is found it will probably only work on some versions of Word or whatever program the exploit is for. Other then exploits there are also things like extension spoofers but they have their downsides as well since they just make use of Unicode characters to reverse parts of the filename.
