### ISSUE TITLE
Nicehash isues

### ISSUE THREAD

**Issue by domen159** [UnamSanctam/SilentXMRMiner#283]
Why are there so many spikes and is not working constantly at the same rate?

![image](https://user-images.githubusercontent.com/46796528/119262574-ff46e400-bbdb-11eb-992d-31fbf06c29fb.png)

**Comment by UnamSanctam** [comment]
Because that's how mining works. On pools it will display the hashrate as shares over time so the spikes are whenever a share is mined and the space in-between spikes is the time you're mining. The different sizes of the spikes are due to the luck based nature of mining (since if a solution is correct is essentially random so you can mine 2 shares instantly or have to wait for a long time). To see the real hashrate you should look fook at the average over a longer period of time.

**Comment by domen159** [comment]
Ok thank you
