### ISSUE TITLE
GPU Mining

### ISSUE THREAD

**Issue by Khizhniak** [UnamSanctam/SilentXMRMiner#290]
I'm wondering if it is possible to regulate the workload of the GPU, if so, why can't we use the GPU resources to mine, because then we can get more?

**Comment by UnamSanctam** [comment]
Well you can technically regulate it by changing the `--cuda-bfactor-hint=12 --cuda-bsleep-hint=100` options in the 'Advanced Parameters' field (although they are already at the minimum I believe). There isn't any global setting for the GPU workload since all of the algorithms work differently. Mining XMR with a GPU isn't that profitable (or intended to be done since RandomX is a CPU algorithm), if you want to mine with the GPU you should probably mine some coin meant for GPU mining like Ravencoin (KawPow, GPU Only) in this miner or something like ETH or ETC with https://github.com/UnamSanctam/SilentETHMiner.

**Comment by Khizhniak** [comment]
Thank you for answering ❤️
