### ISSUE TITLE
Crypt

### ISSUE THREAD

**Issue by SalamnderPro** [UnamSanctam/SilentXMRMiner#299]
Hi, after turning on W Defender there is a detection, is it possible to encrypt the VM protect miner? To increase stealth.

**Comment by UnamSanctam** [comment]
You can firstly enable '"Kill" Windows Defender' and you can also obfuscate it to reduce detections: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by Khizhniak** [comment]
https://github.com/UnamSanctam/SilentXMRMiner/issues/296 <==

**Comment by Fleettelematicssystem** [comment]
at runtime, with the exception of windows defender, all avs are already detecting :( anyone with any solution?

**Comment by UnamSanctam** [comment]
That's usually how it is for any long-term public project since a huge amount of people use it (or misuse it). You either have to modify the miner yourself to make the code unique just for you or find a good obfuscator which not many use, you can find a list of a few here: https://github.com/NotPrab/.NET-Obfuscator although they are also mostly  public projects which will increase their detections as well. Many AVs are also very indiscriminatory, as in they mark every file that has a low number or runs (low reputation) as malware.

This usually isn't a problem though since like 90% of all users only use Windows Defender.

**Comment by Khizhniak** [comment]
Sorry if I repeat the question, but if I encrypted all the dlls and the final file with one cryptor, and then glue the miner with some other .exe file and encrypt the gluing of files with a completely different cryptor, will everything work correctly? I just do not have the opportunity to test the performance.

**Comment by UnamSanctam** [comment]
Yes it should, if you can test it quickly and just see the miner runs (it injects into the chosen process like explorer.exe) then that's all you really need to do since as long as it runs then nothing will impact the performance. After testing it you can run the uninstaller and it will remove and kill everything automatically.

**Comment by Khizhniak** [comment]
By the way, if a miner is already installed on the computer, but without uninstaller, how can I remove it?
