### ISSUE TITLE
How can i set usage of GPU to 20%?

### ISSUE THREAD

**Issue by stroplet24** [UnamSanctam/SilentXMRMiner#30]
How can i set usage of GPU to 20%?
Maybe somewhere in code?

**Comment by UnamSanctam** [comment]
GPU mining does not work that way, GPU usage for Nvidia cards is set by changing the --cuda-bfactor-hint and --cuda-bsleep-hint values in the Advanced Parameters setting and even then you would have to know what you're doing. I would suggest leaving at the levels I have put them.

Also, GPU mining isn't recommended anyways on the new RandomX algorithm that Monero uses since it's horribly inefficient compared to CPU (because it is designed that way).

**Comment by Nox1793** [comment]
But if we enable CPU+GPU isn't it more profitable? 
What you mean it's inefficient?

**Comment by UnamSanctam** [comment]
Yes of course GPU+CPU is more profitable but the CPU would be the majority of the profit since the new algorithm is designed for CPU mining. Also with GPU mining enabled the file size will be bigger and it will be more detectable since it has to include some CUDA drivers.
