### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Khizhniak** [UnamSanctam/SilentXMRMiner#300]
1. What do you think about the configs? For example, create a json file with 

![● Untitled-1 - Visual Studio Code 04 06 2021 15_14_28](https://user-images.githubusercontent.com/57261690/120799676-bbdb6680-c547-11eb-9e4f-2f413a5d8049.png)

and just let people insert json in builder, to create miners automatically.

2. **And how soon there will be an update?**

**Comment by UnamSanctam** [comment]
1. I've wanted to create Load/Save system for a while but it takes a lot of work to do since I have to make it read or write and change all the field in the miner manually which is a lot of code and testing.

2. I'm currently working on a unified miner but there isn't really any need for an update at the moment. And that is a good thing since that means the miner is stable and working.

**Comment by Khizhniak** [comment]
Great!
