### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by Khizhniak** [UnamSanctam/SilentXMRMiner#315]
I tested the miner and noticed that when a person opens the task manager (like a normal person), the processor load drops, and the RAM remains in place, for example, in my case it was 2500 MB and this is quite noticeable, especially if the miner got on a weak PC ...

Are there any hints on this, is it possible to somehow control the load of RAM?
maybe if it is necessary for the miner, then make a delay of 2-3 seconds for the task manager so that the RAM also falls?
Or maybe this watchdog is eating so much memory?

**Comment by UnamSanctam** [comment]
The RAM usage has to do with the RandomX algorithm, the huge pages features (the 2.5 GB of RAM) is required to mine efficiently, you can mine with less but the hashrate will be a lot lower. The reason it doesn't unload the memory it uses is because the 'Stealth' function only pauses the miner. The only real way to also clear the memory would be to entirely stop and clear all the threads but XMRig doesn't really support this in a reliable way from what I know and have tested so I would have to restructure it myself.

**Comment by Khizhniak** [comment]
Can you give an example about hashes?
For example, if the processor mines 500 hashes by 80%, how much will it mine,if mine  less and quieter (you understand)

**Comment by UnamSanctam** [comment]
What exactly do you mean? Let's say you have a CPU that mines 300 H/s per core and it has 8 cores, then if you mine at 80% then it would mine with 8\*0.8=6.4≈6 cores meaning around 1800 H/s (if the CPU cache allows this many cores to be utilized efficiently). If you instead mine with 20% then it would use 8\*0.2=1.6≈1 core which would be 300 H/s. If you mean running it in light mode (no huge pages, so it uses like 256 MB of RAM) then don't bother since it will reduce the hashrate by like 50% or more.

In the next version (the unified silent miner) I can try to make it clear the RAM when 'Stealth' is enabled but I didn't make it that way before since there seemed to be some instability when I did so.

**Comment by Khizhniak** [comment]
Thank you!
It would be great if you tried to do it! I will very much wait for the new version!
