### ISSUE TITLE
minimum payout for nanopool

### ISSUE THREAD

**Issue by Gooduser34** [UnamSanctam/SilentXMRMiner#319]
Hello, can I change the minimum payout of nanopool for xmr mines without disabling the miners or anything else?

**Comment by UnamSanctam** [comment]
All your workers need to use the same password to change the minimum payout. If you can't do that then you can always contact support, some have had success there.

**Comment by Gooduser34** [comment]
I have a botnet with miners, so its not possible for me right ?

**Comment by UnamSanctam** [comment]
If you use 'Remote Configuration' then it's possible since you can just change it but if you don't then not really since you won't be able to make all the workers have the same password unless you don't use any worker names for the miners right now. You could try contacting their support though I have never done it myself so I'm not sure how it would go.

**Comment by Gooduser34** [comment]
It's not that bad, I'll infect more PCs to increase my hashrate, but thanks for answer me fast :)

**Comment by UnamSanctam** [comment]
Good luck with the mining!
