### ISSUE TITLE
What is the Xmrig Operator you use !

### ISSUE THREAD

**Issue by Imormon** [UnamSanctam/SilentXMRMiner#322]
The silentxmrminer seems to be using 100% of the proccesing power, how is that stealthy !!

**Comment by UnamSanctam** [comment]
Set it to a lower percentage then?

**Comment by Imormon** [comment]
Huh! How??! i can't edit the xmrig command line

**Comment by UnamSanctam** [comment]
You can choose the maximum CPU it should use with the "Max CPU" option in the "Mining" tab. It will use that percentage of your CPU cores to mine.

**Comment by Imormon** [comment]
I want it to only use fifty per cent, so it stays under the radar

**Comment by UnamSanctam** [comment]
Yes so select 50% in the "Max CPU" box, how many CPU cores does the computer you ran the miner on have?

**Comment by Imormon** [comment]
Ok i made it work, One more thing what does your name mean, i keep reading it uname scam, are you a scammer, did you pack this silent miner before releasing it, do you have another wallet inside of it, and then after all you wouldn't tell me even if you would. It doesn't work for i just used it for testing but i don't trust like that, i think i'll pass. 
Watch this on YT  v=zONW46d50A0

**Comment by UnamSanctam** [comment]
This is the meaning of my name: https://en.wikipedia.org/wiki/Unam_sanctam, it's Latin. The miner is open source so you can just check the code for what it does and/or compile it yourself. I've been developing this miner for 2 years now and is used by a lot of people so if there was anything like that it wouldn't be used by so many.

**Comment by Imormon** [comment]
huh! Open source! what about the modified Xmrig, i've checked the hashes.

**Comment by UnamSanctam** [comment]
Yes I've modified the xmrig quite a bit since my miner has quite a lot of features that don't exist in the normal XMRig, you can see why I don't share the source for it anymore here: https://github.com/UnamSanctam/SilentXMRMiner/issues/227#issuecomment-861499572. If you'd even remotely checked our repositories which you obviously haven't then you would see that the miners are completely different now since he stopped developing it 2 years ago, I even say `Based on Lime Miner v0.3` at the top of the GitHub and credit him in the miner and on the page itself and furthermore NYAN-CAT has seen my work and gave a +rep to my HF profile when he saw it so I'm not sure what you're trying to say or imply here. You can use the miner or you can not, it doesn't really matter for me since it's free in the first place.

**Comment by Imormon** [comment]
You do you mate, But just don't say its O P E N  S O U R C E, when it's clearly Not, and that 227 comment AKA excuse you choose to plug in the face of everyone who asks for the code of the Xmrig is just Lame, just say i have implemented a backdoor to it, and move on, after all whats the best way to spread a silent miner is by letting other do it for you.

**Comment by Imormon** [comment]
https://www.youtube.com/watch?v=zONW46d50A0

**Comment by UnamSanctam** [comment]
Friend, I don't know what your problem is but you can just replace the XMRig with anything else and it will work just fine or just don't use the miner at all if you're paranoid. You can just sniff the network traffic or reverse engineer it to see what it does, it's not that hard if you have the knowledge how to. Your aggression and wording in this entire issue reminds me of the people who have their own paid silent miners and message me threats to make me take down my miner since it reduces their profits or those who want the new source code to use in their own miners. I don't know if you're one of them but from everything you've written so far that is what it reminds me of though I guess your methods of doing so are quite ineffective.
