### ISSUE TITLE
Which pool to use for a large number of PCs?

### ISSUE THREAD

**Issue by Vadis00** [UnamSanctam/SilentXMRMiner#326]
Hey!
I want to install a miner on ~ 2000 PCs, can you recommend a pool?
Can I get banned from the pool for hidden mining?

And yet, will SilentXMRMiner and SilentETHMiner conflict if you run them at the same time?
Thank you

**Comment by UnamSanctam** [comment]
Yes you can get banned from most pools if they believe you mine on a botnet/have malicious miners. Because of this it's usually best to use xmrig-proxy (for the XMR miner only) or use a pool that doesn't ban. I usually recommend nanopool since they haven't banned before but there has been some issues the last week with the miner (only ETH so far) which could be because of nanopool.

If you use the 'Remote Configuration' option (XMR: https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration, ETH: https://github.com/UnamSanctam/SilentETHMiner/wiki#remote-configuration) then you can also change the pool dynamically if you do get banned so it's not too bad if you choose to mine directly to pools which can ban.

You can run both the XMR and ETH miner at the same time since the XMR one will use CPU (Don't enable 'GPU Mining') and the ETH one will use the GPU.
