### ISSUE TITLE
Windows killer

### ISSUE THREAD

**Issue by Gooduser34** [UnamSanctam/SilentXMRMiner#330]
Hello, If I use a miner who needs admin rights to "kill windows deffender" and i bind this miner with other exe files, everything still works?

And is the miner started even if the admin rights are not accepted when starting?

**Comment by UnamSanctam** [comment]
If the binder supports running as administrator it will work, you can also change the manifest file with Resource Hacker to make it run as administrator if that option does not exist.

It won't start without administrator since Windows itself is what handles that and not the program. There is technically one method of doing that but it's not very reliable.

**Comment by Gooduser34** [comment]
kk, thanks for hekp bro :)

**Comment by UnamSanctam** [comment]
No problem, good luck with mining

**Comment by Gooduser34** [comment]
Thanks, what is diffrent to max cpu and idle mining ?

**Comment by UnamSanctam** [comment]
Max CPU is the normal CPU it will use while the computer is active, if you enable "Idle mining" then it will use the Idle CPU amount of % while the computer is idle (not having any mouse or keyboard input for the "Idle wait" amount of time). You can see more explanations here https://github.com/UnamSanctam/SilentXMRMiner/wiki#max-cpu

**Comment by Gooduser34** [comment]
Thanks bro :)
