### ISSUE TITLE
Online Downloader

### ISSUE THREAD

**Issue by vpts1202** [UnamSanctam/SilentXMRMiner#332]
Hello
I have just gone through your product (which is looks very-very good), so I have couple of short questions, please:
As I understood, after I will set up the miner with my chosen pool and wallet-address I will get some kind of file that will be hosted in GitHub.  So my question #1: where I will get url/link to it? The question #2: Is it direct download(i.e. as soon as  visitor click to url/link it started download/install), or it will require some further action?
Thanks
PS: I have just sent to you request via Discord to add me to your friends list(just in case if I will have further queries during set up)

**Comment by UnamSanctam** [comment]
All "Online Downloader" does is that it makes the miner download the actual miner from https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/xmrig.zip instead of embedding it directly into the file to reduce the file size mostly to reduce detections. It's all automatic and there's nothing really that you have to do yourself.

**Comment by vpts1202** [comment]
Thank you for your kind feedback.
Looks like I did not formulated my query clear.
I have just sent you message via Discrod to clarify.
Thanks again.

**Comment by vpts1202** [comment]
Could you be so kind to look at your Discord please? I built the miner and all looks great, but still I need a little bit more of your support. I have placed my queries in Discord.
Thanks
