### ISSUE TITLE
Implement Monero Ocean's algorithm switching for top profit

### ISSUE THREAD

**Issue by ezanchi** [UnamSanctam/SilentXMRMiner#340]
Hey thanks for this awesome tool!

Is there any chance you can implement Monero Ocean's XMRig version that allows for it to switch algorithm if there is a better one?

Links:
https://github.com/MoneroOcean/xmrig
https://github.com/MoneroOcean/xmrig-proxy

**Comment by UnamSanctam** [comment]
I won't implement that because during the benchmark it does some of the algorithms it benchmarks freezes some computers so it would defeat the purpose of a stealth miner.

**Comment by ezanchi** [comment]
Alright sounds reasonable.

So the most profitable algorithm is rx/0?

**Comment by UnamSanctam** [comment]
Well, most CPU algorithms have mostly the same profitability, you should mine the coin you believe will rise the most in the future since they will be the most profitable to mine before it rises. I mine a lot of different currencies like Turtlecoin (before the V2 release), Kevacoin, Monero, Wownero so I don't especially mine on one pool.
