### ISSUE TITLE
Visible Address

### ISSUE THREAD

**Issue by DxDvmi** [UnamSanctam/SilentXMRMiner#342]
Can the monero miner be found & decrypted so the Monero Address the Target is mining to, is visible after the decryption?

**Comment by UnamSanctam** [comment]
Yes of course, the traffic could just be sniffed anyways so there is no certain way to could ever hide it if the person really wanted to find out since you need to send the address to the pool to mine. Monero addresses are private though so as long as you haven't shared that address anywhere that could be tracked to you like posting the address on a forum with your email which then they would know that the Monero address belongs to that email then there is no way to track who the address belongs to.

**Comment by DxDvmi** [comment]
Alright thanks, but how do you cash out then if you can get traced? So it useless to cash out on an Exchange.

**Comment by UnamSanctam** [comment]
The transactions cannot be traced with Monero, only thing which can be traced is if you post the address somewhere, if you were to post your address here in the issue then I would know that the address belongs to you.

**Comment by DxDvmi** [comment]
Thanks alot 😊
