### ISSUE TITLE
meta

### ISSUE THREAD

**Issue by bashicq** [UnamSanctam/SilentXMRMiner#349]
1) Didn't understand how to use pastbin. How to use my link with the config, and where to put it in the builder?

2) I read a lot, but I did not find the answer to my question. How to configure and run xmrig-proxy? On which server, what do you need for this, what operating system to use for this? And so on. I would really appreciate it if you could help me, and in the future you would add this information to your wiki.

3) What is the probability that the miner will find the antivirus, provided that running as an administrator is enabled, adding Windows defender to the exceptions, and installing in system32?

4) Сan the pool get rid of my workers on its own?

**Comment by UnamSanctam** [comment]
1. Open "Advanced Options" and enable 'Remote Configuration' and paste the 'raw' link there.
2. Running xmrig-proxy requires some computer knowledge so writing a tutorial for that wouldn't be very fruitful since it would be a very very long tutorial to help everyone depending on the setup they want. Download https://github.com/xmrig/xmrig-proxy and change the config.json to suit your setup and then just run the proxy, you can just connect to it with the IP and port of your proxy server.
3. While the exclusions for "Bypass Windows Defender" are there Windows Defender theoretically should never find the miner. Other then that it depends on the obfuscation that you use.
4. Any pool can ban you for any reason, though mostly it's only done if they believe you are mining on others computers/a botnet. If you use xmrig-proxy and/or the 'Remote Configuration' then you can just change it if you get banned, though if you use xmrig-proxy the chance of you getting banned is near zero since all the traffic will come from the proxy.

**Comment by bashicq** [comment]
Oh, thanks for your answers.
>2
Is it possible to use ubuntu server? and in any way synchronize it with the free githab domain? And another question, the traffic immediately after compiling the proxy will go to the pool? Nothing needs to be corrected there?

**Comment by UnamSanctam** [comment]
Yes you can use ubuntu, I use that for all my servers, just download the linux version. I do not believe you can point a GitHub domain to an IP so you wouldn't be able to point it to the proxy. The proxy will get the jobs from the pool and distribute them to the miners as subjobs (splits each job into 256 subjobs) which means that for the pool every 256 miners will only be one pool connection, so 2560 miners will be 10 connection to the pool. The miners will then submit those subjobs to the proxy which will then submit them to the pool, all of this is automatic so you only need to edit the config.json and run the proxy.

**Comment by bashicq** [comment]
Please forgive my ignorance. I meant the domain that will be specified as the input address from which in the future traffic will go to the pool. The thing is that servers often change their ip addresses, and using a free domain (example: mylitledomen.github.com) would save me money and simplify the task. From this follows another question, how to syncrify the domain and the server?

**Comment by UnamSanctam** [comment]
I don't believe GitHub allows you to specify the IP that their subdomains point towards so you wouldn't be able to make the domain point towards the server IP. You would need a domain where you can change the DNS records or use some other service that changes the DNS records automatically.

**Comment by bashicq** [comment]
Thanks, you helped me a lot. Do you think to close this thread, or leave it for such meta questions?

**Comment by UnamSanctam** [comment]
No problem, I'll close it, if there are any new questions opening a new issue is fine.
