### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by Smirksx** [UnamSanctam/SilentXMRMiner#350]
I have no idea of about mining and stuff but isn't it dangerous to use your password to change the minimum payout cause people can extract it including my xmr address?

**Comment by UnamSanctam** [comment]
Doesn't really matter, all they can do with the password (if you set it to something like 123456) is change the minimum payout but if you also start mining with another password after you've changed the minimum payout then they can't change it since all workers need to use the same password.

For the XMR address, the XMR blockchain is privacy driven and as such you can't track addresses or transactions or anything else so exposing your XMR address (should use a subaddress that you only use for mining) isn't trackable unless you post the address somewhere like a forum (or God forbid; Facebook) and it gets linked to you that way.
