### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by impacts2** [UnamSanctam/SilentXMRMiner#351]
Hi bro what binder do you suggest i use cause i keep finding ones with virus

**Comment by UnamSanctam** [comment]
You can try this [Dream_AIO_-_Unam_Sanctam_Custom.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6888510/Dream_AIO_-_Unam_Sanctam_Custom.zip) though I'm not sure how many detections the bound file will have.

**Comment by impacts2** [comment]
1. If I were to use

**Comment by UnamSanctam** [comment]
1. If you mine on your own computer then the IP will be shown to the pool (since you connect to it) but to nothing else. If you mean mining on other computers then no, the miners will have no sort of connection to you and they will only connect to the pool and mine from there.
2. If it doesn't reach the requirements (no GPU, not enough VRAM or too old drivers) then it will just do nothing and won't really take any resources.
3. Depends on what exactly you do, if you mine directly to a pool with an XMR address that you've never exposed anywhere then theoretically nothing can be traced back to you (don't forget to use a VPN to check the pool since the pool can log IPs). The things which can trace you is if you check the pool you mine on then they might log your IP (most websites log the IP of the visitors on some way, even GitHub of course), the other way is if you post the XMR address somewhere else like a forum (or God forbid; Facebook) then of course anyone will know that the XMR address you post belongs to you. Other then that there is nothing in the miner itself which can be used to trace you so the only things which can really trace you are things which normally tracks all users online which aren't specific to anything like mining. And it's always best to use a VPN.
4. No it will be a new miner so it will be different from the two current ones though the current XMR and ETH miners will still work fine for a long long time.
5. All my projects are free and will always remain free.

**Comment by impacts2** [comment]
So if my understanding for #1 is correct there won't be any risks if I were to run xmrig on main pc right? (Cause I saw an issue on this project were someone was using a vps or vm not sure for his xmrig)

**Comment by UnamSanctam** [comment]
No there aren't any risks in and of itself, the pool will of course know your IP though (since when you connect to something you "use" your IP), if you don't want to expose your IP you can use a VPN (though some pools block some VPN IPs). The thing people can run on a VPS is xmrig-proxy which you can use as a proxy between the pool and your miners so that the pool won't ban you since some pools will ban you if they believe you are mining with a botnet, though using xmrig-proxy isn't required in any way. And some test the miner on a VM since they don't want to "infect" their main computers (though you can just run the uninstaller to remove the miner), it's generally good to always run things which could be malicious inside a VM.

**Comment by impacts2** [comment]
Thanks, last question then I'll close this again (sorry for being annoying :v)

If the pool were to close my account on their site would I be able to recover the stuff I got? (I know nanopool doesn't do that like you said but what if they suddenly started blacklisting people for multiple mining bots)

**Comment by UnamSanctam** [comment]
Depends on the pool, some can allow you to withdraw what you have left. If you use https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration then you can change the pool or wallet address if you get banned.

**Comment by impacts2** [comment]
Okay thanks.
