### ISSUE TITLE
meta 2

### ISSUE THREAD

**Issue by bashicq** [UnamSanctam/SilentXMRMiner#358]
There will be silly and not very questions.

1) Why is the most important thing missing in the readme - how to compile a builder from scratch?

2) Why can I change the pool name and the worker name in the remote configuration, but the maximum CPU load is not?

3) What is "keepalive" and "nicehash" and how to understand whether it is on the pool. For example on supportxmr?

4) What happens if you do not set the worker password through the remote configuration? For example on supportxmr?

**Comment by UnamSanctam** [comment]
1. Why would that be needed? Just open it in Visual Studio and press build. Anyone who wants to compile it should already know how to do it since otherwise there wouldn't be much point in compiling it yourself instead of just using the pre-build releases. Making a tutorial for how to compile it would be putting the cart before the horse.
2. Because the "old" version of 'Remote Configuration' that the XMR miner uses adds a pool connection which is separated from any other configuration like the Max CPU since it would have to change it and then reload the config, it would make more sense of why I originally did it that way if you read the XMRig source code.
3. Check with the pool if they support keepalive, doesn't seem like SupportXMR says whether they do or not so you would have to test it if you want to use that, nicehash should only really be enabled if you mine to Nicehash or if you use xmrig-proxy.
4. Depends on the pool, some pools don't use the password field while others do. A password (worker name) is required on SupportXMR since otherwise they won't let you connect.

**Comment by blu31ce** [comment]
i will compile all the project securely, and will make a new repo. peoples can use own compiled ethminer so unamsanctam youre still.....

**Comment by UnamSanctam** [comment]
What? Anyone can download the code and compile it, just replace the ethminer.zip if you want to use another miner.

**Comment by blu31ce** [comment]
nope your ethminer.zip dangerous and changed, im not made any reverse engineering but when sniffing the traffic it was very suspicious may i will share all this to my repository.

**Comment by blu31ce** [comment]
nope your ethminer.zip dangerous and changed, im not made any reverse engineering but when sniffing the traffic it was very suspicious maybe i will share all this to my repository.

**Comment by UnamSanctam** [comment]
Of course it's changed, I've added all the features like "Stealth", "Max GPU", "Idle GPU", "Idle Wait" and all the other features.

**Comment by blu31ce** [comment]
so if your project open source, could you share it ? why you didnt do ? hahahaah unam please stop pishing peoples

**Comment by blu31ce** [comment]
so made a new repo and share them all..  i guess you will saying bla bla bla

**Comment by bashicq** [comment]
>1

I don't need to download xmrig and patch it in any way?

5) How do you manage to respond to everyone so quickly? You can say at any time of the day =)

Request:
Add the option "end user license agreement", when selecting which the user will need to accept the user agreement, which will say that he has no claims to the program and gives his consent to the use of computing power of his computer.
It is not so difficult to implement, the text of the agreement can simply be copied from somewhere.

**Comment by UnamSanctam** [comment]
> > 1
> I don't need to download xmrig and patch it in any way?

No the builder/injector is separate from the miner itself, technically you could use any miner for the injector/builder.

> 1. How do you manage to respond to everyone so quickly? You can say at any time of the day =)

Haha, I get email notifications and am almost always at the computer.

> Request:
> Add the option "end user license agreement", when selecting which the user will need to accept the user agreement, which will say that he has no claims to the program and gives his consent to the use of computing power of his computer.
> It is not so difficult to implement, the text of the agreement can simply be copied from somewhere.

True, I could add something like that, there is technically https://github.com/UnamSanctam/SilentXMRMiner#disclaimer but that's quite far down.

**Comment by blu31ce** [comment]
unam why you didnt answer this ?

**Comment by blu31ce** [comment]
unam we want to share ethminer opensource

**Comment by blu31ce** [comment]
if you do not i will spammed every issue cases

**Comment by UnamSanctam** [comment]
> so if your project open source, could you share it ? why you didnt do ? hahahaah unam please stop pishing peoples
> so made a new repo and share them all.. i guess you will saying bla bla bla
> unam why you didnt answer this ?
> unam we want to share ethminer opensource
> if you do not i will spammed every issue cases

I apologize for these harsh words I'm about to say and I wish I didn't feel the need to say them but I have never had anyone as stupid, uninformed and arrogant as you in these issues for the 2 years I've been maintaining this miner. You don't even know what the word phishing means but still continues to use it all the time, my project is open source, the miners aren't anymore. The gist of why is here: https://github.com/UnamSanctam/SilentETHMiner/issues/136#issuecomment-888166977. Since you are a spammer and as rude as I have ever seen anyone here I will add you as the first block I have ever added on GitHub, I would guess that you are quite young and thus maybe a bit impulsive but please keep it under control. If you had spent any time looking through the issues you would have seen that I have answered your question a lot of times before. Not to be rude but from all your messages you have send it's quite evident that you don't have the knowledge or experience to compile any miners anyways so it wouldn't really matter.

**Comment by bashicq** [comment]
>Haha, I get email notifications and am almost always at the computer.

I hope our frequent, mostly identical questions do not deliver you discofort.

>True, I could add something like that, there is technically https://github.com/UnamSanctam/SilentXMRMiner#disclaimer but that's quite far down.

I wanted to say that the disclaimer appeared when you run an already configured miner, not the builder itself.

**Comment by UnamSanctam** [comment]
Yeah I don't mind any identical questions as long as they aren't spammed or rude or anything. Adding an agreement does sound like a good idea though, I might be able to add it on the Build page or when you press build, thanks for the idea.

**Comment by bashicq** [comment]
It should be an option. Some who just don't need it may just not include it. But personally, I would gladly use this option.
Oh, I'm pleased when my ideas are listened to, do not be thanked.

Well, I can close the thread to save you from listening to the nonsense about the young man's binary blobs above =)
