### ISSUE TITLE
what settings are good for myself

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#376]
im confused what settings i should use
should i use watchdog
should i enable the obfuscate
should i enable defender killer
should i enable online download
what process should i make it inject to that wont mess anything up if i close it
should  i add the option to put it in sys32

**Comment by UnamSanctam** [comment]
It depends on what you want it to do.

- "Watchdog" is always good to enable.
- "Pause for Obfuscation" should be used if you want to obfuscate all the different parts of the miner to reduce detections.
- "Bypass Windows Defender" is good to use but requires administrator privileges.
- "Online Download" will download the actual miners from online so that the initial file size becomes really small (like 30-40kb) and it also reduces detections, the downside would be if it ever gets taken down, though there are backups so it should be fine.
- You can inject it into any of the programs, it won't really make any difference functionally.
- You can, it requires administrator privileges but makes the program look a lot more trustworthy and users will probably be scared to remove something from System32.
