### ISSUE TITLE
request

### ISSUE THREAD

**Issue by rebelsparx** [UnamSanctam/SilentXMRMiner#38]
hello i am thankful you have made the file i have a small request if possible for adding more like 3
do have a problem though if possible for help with 

1. so set a new hash rate for Testers like 10% to 80% on one click 
2. A windows Exe to install with updates auto rolled out and updated via client
3. Possible to make it like a Bot net so any one that is using for a Gain can stop any old runners and update with Few files wean they up date the proxy

my small prob i dono if me or what ever i used it say 15 days or more ago wean to load it and got the Code file not the File Click and make UI 

other then that please keep the good work up  

![image](https://user-images.githubusercontent.com/59022886/106156518-88439680-6179-11eb-91ee-84e54aca60b9.png)

**Comment by UnamSanctam** [comment]
I have no intention of adding any kind of control panel or auto-updating since it would decrease the undetectability of the miner and require you to host your own servers and for the miner to connect to it. Secondly when the miner is injected the only thing remaining is XMRig and nothing else so there is no easy way for me to add much control. XMRig does have it's own API where changing the config is technically possible but you would have to port forward a port on the clients network and computer for it to work and then add the API settings to the parameters https://xmrig.com/docs/miner/command-line-options, you would then go to http://workers.xmrig.info/ and add the worker by adding it's IP and port but since it requires port forwarding it's not very simple to do.

Auto updating the miner could maybe technically be possible but the XMRig binary is encrypted and embedded inside the miner executable so it would be hard to update it reliably, code that connects to the internet and downloads files is usually detected by many antiviruses as well.

If you want to be able to update and change the miners I would advise you to use some kind of RAT instead and then install and update the miner through that.

If you want to open the code and compile it yourself you have to download Visual Studio and open the .sln file.
