### ISSUE TITLE
wont infecting yourself start to degrade your cpu and gpu?

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#380]
im assuming that it you leave the miner mining on your pc constantly wont it start to ruin your specs?
if i would run a miner on my pc id use 20% all the time and like 60% when idle

**Comment by UnamSanctam** [comment]
The CPU will basically degrade absolutely nothing so that's not a worry, the GPU could theoretically but it would take a few years probably, the only real thing that could degrade would be the fans or something. You could probably mine for a few years without noticing much of a difference. The thing that degrades the parts is if you have a very high temperature but that isn't unique to mining but just to computers in general.
