### ISSUE TITLE
when i run the miner for myself disk usage and memory goes to 100%

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#382]
i set the miner to use only cpu and at all times it uses 30% and idle 60%
as soon as i ran the miner which was injected into windows explorer  it jumped to 100% disk and memory usage
and there was no added startup process which i made sure was enabled
the miner is here  https://tmpfiles.org/88410/miner4self.exe
if u wanna test it out and see whats wrong with it

**Comment by UnamSanctam** [comment]
Is that using the newest version 1.4.4? How many cores does the machine you're running it on have?

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Is that using the newest version 1.4.4? How many cores does the machine you're running it on have?

its the newest version i have 8 cores

**Comment by UnamSanctam** [comment]
The miner doesn't use any disk so if it's using any then it isn't from the miner. If it's using any disk then that's probably since you've run out of RAM and it's using your pagefile instead. RandomX (The Monero algorithm) uses 2GB of RAM to mine, you can mine other cryptocurrencies that uses other algorithms than RandomX since most other algorithms don't really need any RAM.

And dwm using 5GB is just classic Windows haha.
