### ISSUE TITLE
WD bypass and miner problems

### ISSUE THREAD

**Issue by olafeqwtf** [UnamSanctam/SilentXMRMiner#384]
Hey I have a problem, i have created a miner with everything set up, run as administrator And WD bypass turned on but Windows defender still detects the program

so WD bypass doesnt work well and the miner is not really usefull when it can be detected

second problem is that when someone will allow program in WD And try to run it, after a startup time (the time it waits before mining) the window pops up and it asks „would you like to run this program it is highly risk” or something like that and it shows that the program is „services64” and after you allow it nothing happens, id doesnt mine and just freezes. In task menager i can see services64, Chrome.exe (my miner), but there is no process mining (explorer) so it is broken

is that .NET framework version problem?

**Comment by UnamSanctam** [comment]
The "Bypass Windows Defender" adds exclusions when it's run so that it won't be detected in the future, it doesn't have much to do with not being detected before that. The miner was undetected with that option for a month or two (got detected maybe a few days ago) but since there are a few hundred thousand miners (that I know of) it gets detected eventually since all the code gets marked as malware. If you want to decrease detections you should use an obfuscator or any other method to reduce detections, https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections. **No** program that can be theoretically classified as malware that is on GitHub is undetected right out of the box without any effort done to change it since it can't really be due to the public nature of the program and code.

The problem with the popup asking for privileges seems to have something to do with the computer building it, try using another computer to build it.

**Comment by olafeqwtf** [comment]
Ok, thanks i will try and Herę is the popup
![Uploading BB70713D-1550-452D-9F3B-C862EDB42113.png…]()

**Comment by olafeqwtf** [comment]
![3929C20F-6D6B-4D98-8239-FECB6D68166D](https://user-images.githubusercontent.com/79247494/128647163-0e78db4d-cb54-45de-9679-2f48cc1d2050.png)

**Comment by UnamSanctam** [comment]
Yeah that seems to appear when some computers build it (has only been reported like 3 times now in the 2 years I've been making this miner), seems to be some issue with some part of Windows or the .NET Framework or something. Can also happen when you sandbox it since when you grant permissions in the sandbox it's not persistent across all program starts.

**Comment by olafeqwtf** [comment]
Oh that is bad because i have no other computer to build it on

**Comment by olafeqwtf** [comment]
It is weird tho because on the comp i build it it works just fine

**Comment by UnamSanctam** [comment]
Where do you test it to get that popup?

**Comment by olafeqwtf** [comment]
My friends pc

**Comment by UnamSanctam** [comment]
Yeah then from experience that seems to happen because of the computer it was built on.

**Comment by olafeqwtf** [comment]
Can you help me with this build? I mean with detection and this weird build problem

**Comment by UnamSanctam** [comment]
Well, you could probably set up a VM and built it inside that for the build problem. For detections, any help I would give to you I would also have given to many others thus making it not very undetected since a lot of people would use it. You can try using any obfuscator like ConfuserEx https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections to see if there's a difference.

**Comment by olafeqwtf** [comment]
Can miner be run to test it on VM?

**Comment by UnamSanctam** [comment]
Yes.

**Comment by olafeqwtf** [comment]
Ok, thanks for help
