### ISSUE TITLE
WHIC CRYPTER AND SECOND QUESTION 

### ISSUE THREAD

**Issue by legitdark00** [UnamSanctam/SilentXMRMiner#39]
Hello bro, firstly thank you for updating this miner, ı want to ask you two question about this miner.
1-)Whic crypter should ı use it for this SilentXMRMiner? .Net or Native Crypter. Is there a crypter you can recommend me ?
2-) I am thinking to use supportxmr pool and ı run this miner lots of VDS but supportxmr allow lots of miner? if ı use 443 or 9000 ports, probably supportxmr doesn't block me right ?

**Comment by UnamSanctam** [comment]
Sorry I don't use any crypters but my miner bypasses antiviruses like Windows Defender by default, you can use any of the .NET Obfuscators online to decrease detection rate safely.

SupportXMR bans any address that it believes to be a botnet or has malicious miners, this can be bypassed by using something like xmrig-proxy but that is advanced to set up. If you don't want to use xmrig-proxy  then use a pool that doesn't ban people like nanopool.

**Comment by legitdark00** [comment]
I don't understand bro do you have private miner ? because many ativiruses program detected miner. If ı use .Net crypter miner is fud and working correctly right ?
And nanopool doesn't ban people right ?

**Comment by UnamSanctam** [comment]
No but because my miner uses RunPE/injection it remains undetected from antiviruses like Windows Defender but if you want to make it undetected from antiviruses that uses heuristic analysis you can use a crypter/obfuscator. Most crypters only keep it FUD for a while though of course until the stub is detected.

And yes, nanopool doesn't ban people as far as I know, since they can't exactly say it outright.
