### ISSUE TITLE
Would you consider writing a paid program or consulting?

### ISSUE THREAD

**Issue by kronikcokus** [UnamSanctam/SilentXMRMiner#398]
if yes, please drop info for contact.
i need all in one miner that no effort to configure for users just run by my rules.

it just like about the limitation of the miner program and other issues, to give an example;;

if user have +4GB gpu mine etherum
if user have smaller than 4GB gpu mine xmr 
if user have no gpu work with cpu

if user have opened game or uses 3D parameters of gpu limit -gpu- cuda mining as %30.
etc..
etc..

**Comment by UnamSanctam** [comment]
I don't do any paid work, you could add the VRAM checks in the Program.cs yourself since that is probably where it would be best to have it, though checking the VRAM isn't easy. Even then you can still mine with GPU on computers with less than 4GB of VRAM with other Ethash coins or ETC, and you can also mine XMR while you mine ETH/ETC (or any other Ethash coin) since it uses the CPU and not the GPU. 

For the GPU limit that won't really affect any programs since the miner will automatically use less if any other programs needs it, the biggest problem is the VRAM it uses but you can just add programs it should pause for in the "Stealth Targets".

**Comment by djmessaoud** [comment]
Contact me discord Mesut#1328
