### ISSUE TITLE
saving builder settings

### ISSUE THREAD

**Issue by shinobiclan** [UnamSanctam/SilentXMRMiner#400]
Just a wish to add, if possible, save the builder settings. 
In general, on my own behalf, I will say that the miner is working successfully.
I saw a single case when the smartscreen blocked the download, maybe it's just an accident

**Comment by UnamSanctam** [comment]
Yeah I've wanted to add a save/load for a long time but there's a lot of code to be written and checked since I have to hard code a save/load thing for each field and option available (and find a good format to save it in, I guess only XML is viable without any external libraries).

SmartScreen appears when the file doesn't have a reputation. Only ways to get the file reputable is for Microsoft to add it into their database or to pay them money for a certificate. Sometimes adding assembly information can alleviate it.

**Comment by shinobiclan** [comment]
clearly understood thanks
I just sometimes get confused in the settings
As I understand it, it is best to set the load during use from 20-40 and at the time of downtime from 88-100?

**Comment by shinobiclan** [comment]
![SharedScreenshotывывы](https://user-images.githubusercontent.com/35500797/129934214-0fab111a-52a1-4821-8d8b-aad6dde2d44e.jpg)
for me personally, sometimes it rises very high, then drops sharply

I work this way, everything is fine

**Comment by UnamSanctam** [comment]
Yes, that graph looks that way since mining is luck based so you should always look at the average over time.

**Comment by shinobiclan** [comment]
clearly understood thanks
the question is closed =)
