### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by boff64** [UnamSanctam/SilentXMRMiner#42]
Hi, can windows defender disabler and anti-sleep be included? Black windows sometimes flash also. Thank you.

**Comment by UnamSanctam** [comment]
Anti-sleep will be added in the next version, Windows Defender disabler is impossible unless the process has admin permissions to run some commands and modify the registry and even then it's hard to do so that won't be included. The CMD window opens for a split second because the window class has to be registered but I will also try to minimize that in the next version.

**Comment by nakurnjak** [comment]
Hi, I also think that anti sleep is really good to include. When I next update will be released ? CMD popup is not that bad when cpu is turned on, but it is really bad when gpu is working. Overall great work

**Comment by UnamSanctam** [comment]
Anti-sleep and hiding the command window has now been added in the new version.
