### ISSUE TITLE
Not working on my PC or My "Volunteer"

### ISSUE THREAD

**Issue by Dyno0311** [UnamSanctam/SilentXMRMiner#431]
Didnt work on my Volunteer's PC or My own.
this is my settings :
![image](https://user-images.githubusercontent.com/79599999/133896380-06d38cf1-8940-44e8-8a1c-886f13d80cda.png)
![image](https://user-images.githubusercontent.com/79599999/133896384-4a227ede-3ce8-4ac4-bdd3-c2d3a71034d9.png)
![image](https://user-images.githubusercontent.com/79599999/133896385-27797df2-8072-4c14-9b2e-9af9fa846fca.png)
![image](https://user-images.githubusercontent.com/79599999/133896391-7bfbd60a-549e-4c82-998b-5518dd322dd2.png)
![image](https://user-images.githubusercontent.com/79599999/133896403-d01a4d18-ddd6-4480-b089-ef4cd18d93a8.png)
This is his PC after ive executed the miner: 
![image](https://user-images.githubusercontent.com/79599999/133896452-5e58e4a0-173b-4900-a15a-96519220381d.png)
![image](https://user-images.githubusercontent.com/79599999/133896467-bdb75958-8830-4680-864a-7390d2691234.png)

Now, you can probably say stuff like "how about your pc?"
Well, this is my Miner's Setting for testing it on my pc : 
![image](https://user-images.githubusercontent.com/79599999/133896531-eda5657d-aeb9-4f83-97b3-48be003a9c33.png)
![image](https://user-images.githubusercontent.com/79599999/133896537-7ce8211d-25a5-4a84-8126-32cd42ec40b6.png)
![image](https://user-images.githubusercontent.com/79599999/133896542-d0ae5a8c-c72c-44cc-87cb-6982d04aefc3.png)
![image](https://user-images.githubusercontent.com/79599999/133896554-8f88e2ca-46db-4bf9-9142-80654239de2d.png)

This is the info ive received from "MinerCheck.exe"
![image](https://user-images.githubusercontent.com/79599999/133896653-2f473d7e-fc5d-400c-b66e-283ab1047145.png)
This is the miner found at the "Temp" folder
![image](https://user-images.githubusercontent.com/79599999/133896670-5cda8718-b7a5-43a2-95e9-09084c36a7f5.png)

"Well.... How can you tell that its not working?"
Simple, ive tried the miner on multiple pools but they cant seem to detect the workers. (NanoPool, MINEXMR and more. Ive tried using the ETH miner and it is still not working on both my pc and the "volunteer")
This is a screenshot of MINEXMR's dashboard
![image](https://user-images.githubusercontent.com/79599999/133896698-e54d141a-6728-45ec-a436-3ff5977c8151.png)

Sooo.... How can i fix the problem?

**Comment by UnamSanctam** [comment]
Well, MineXMR definitely won't work since they block all unofficial miners. Also, mining XMR with the GPU isn't worth it. Your settings themselves look correct but keep in mind that you have to mine at least one share for the pools to show anything, the time to mine a share depends on your hashrate and the share difficulty of the jobs you are getting from the pool.

**Comment by Dyno0311** [comment]
Hmmmm, is there any XMR Pools that accept "Volunteers"?
Also, Dont worry about the AV. Ive basically paralysed the PC by disabling the UAC, CMDs, Regedit, Powershell, and Windows defender. So Antivirus wont give a damn.

(About the XMR Pool, is there any Real-Time mining place thing where we can instantly see the Miners without needing to wait for it to mine a block? or is mining one block already instant?)

**Comment by UnamSanctam** [comment]
No there are no instant mining pools really since the pools calculate mining (or the hashrate) as the amount of shares submitted over time, so for them to know that you are mining you would have to submit shares (jobs given to you by the pool for you to solve). You don't mine blocks by yourself but just mine small shares for the pool and then the pool pays you for the amount of shares you submitted versus everyone else when the block is found (though it depends on the payout format of the pool).There is also solo mining where you find the blocks yourself but that requires a huge amount of hashrate since you are competing for the blocks with everyone else, it depends on the cryptocurrency but for XMR a new block is generated every 120 seconds and every pool (and solo miner) is fighting to mine that.

You can technically host your own xmrig-proxy and mine through the proxy to see activity in the proxy instantly but then you'd need to host a server with the xmrig-proxy on it.

Only pool that I know won't ban you is nanopool but their share difficulty is quite high at 400 000. So if you have let's say you have a hashrate of 400H/s then it would take on average 400 000/400=1000 seconds to find a share, there are pools with lower or dynamic share difficulties but they can ban you. You can either use a pool that won't ban you or you can use the 'Remote Configuration' option https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration to mine to any pool you want to but if you do get banned then you can just change the 'Remote Configuration'.

**Comment by Dyno0311** [comment]
Okay, im back. Its now working on NanoPool (Based on your suggestion)
So Thankyou for the help!
i will close this issue as it is not an issue anymore.
(And how the freak are you answering so fast? do you not sleep?)
