### ISSUE TITLE
do i need a password for a miner if i have just the miner name

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#434]
https://anonfiles.com/5a7988I5u2/Screenshot_106_png
do i need to put a password?
i looked at the shares on nanopool and i have 1 worker, but im sure others have downloaded and ran the file

**Comment by UnamSanctam** [comment]
No nanopool doesn't use the password field, but yeah you should only have one worker since you use the worker name 'click' meaning all miners will mine with the worker name 'click'. You can use something like {COMPUTERNAME} if you want each computer to have a separate worker name (in this case their computer name).
