### ISSUE TITLE
Which pool should I use

### ISSUE THREAD

**Issue by mujistic** [UnamSanctam/SilentXMRMiner#437]
Hello again Unam,
I just need your advice on this.
Which pool should I use that is stable and allows for unlimited number of workers apart from nanopool? Nanopool is so buggy and frustrating especially for etc which doesn't show worker names and I also realized that I can't mine with both XMR and ETH without one of them stopping to let the other mine (I used different names for both), though I'm not sure if that is a problem from the pool.

**Comment by UnamSanctam** [comment]
Nanopool is probably the only one that doesn't ban and allows any amount of workers, or it is at least the only I know doesn't ban, but you can use 'Remote Configuration' https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration and mine to any other pool and if you do get banned then you can just change the pool in the 'Remote Configuration'. For ETC you can try Ethermine, it does say in their Term of Use that they will ban you but from what I know it's not that common, for Monero you could try MoneroOcean and if you do get banned on either then just change it in the 'Remote Configuration'.

Both miners will work at once since they don't even really know of each others existence, don't forget to have "GPU Mining" disabled for the XMR miner and for both miners "Filename" in the "Install" tab to be different from each other.
