### ISSUE TITLE
meta

### ISSUE THREAD

**Issue by bashicq** [UnamSanctam/SilentXMRMiner#440]
1) Does the probability of finding a miner increase if:
- both "xmr" and "eth" are installed in the same directory (AppData)
- if two miners are used simultaneously

2) What is more profitable to mine eth or etc?
I just know that for eth mining, you need a video card with at least 4 GB, otherwise nothing will work. Maybe things are a little easier with etc and its mining is more profitable on a large number of weak computers?

3) Is it better to install miners (xmr eth) in different directories?

**Comment by UnamSanctam** [comment]
1. Depends on the user, having both miners at once won't really increase detections, the XMR miner is difficult to detect for the user in the first place unless you set the Max CPU very high. Though putting them in separate directories can generally be good.

2. As you said ETH is more profitable but requires a better GPU while ETC is less profitable but requires less to run. It really depends on what kind of GPUs your miners will have, though usually ETC can be better since it uses less VRAM and will thus impact the user less leading to less user detections.

3. I would put them in separate directories just since it's possible, since if one program gets found then the other won't necessarily be found.

**Comment by bashicq** [comment]
> I would put them in separate directories just since it's possible, 

So?
UnamBinder -> Drop location: Temp (xml and eth) ->
- XMR is installed in Appdata
- ETH is installed in the UserProfile
Only now I noticed that there are more location options in UnamBinder than in any of the miners :)

> since if one program gets found then the other won't necessarily be found.

Even if we are talking about an antivirus search?

**Comment by UnamSanctam** [comment]
Yes, those options should work good, separate locations will make it harder for the user to detect it/find it suspicious, antiviruses couldn't care less where they are.

**Comment by bashicq** [comment]
Understood, thank you.
