### ISSUE TITLE
Is there any way to check if the file you built works?

### ISSUE THREAD

**Issue by Navajaa** [UnamSanctam/SilentXMRMiner#454]
Title. Want to 100% make sure it works before I use it.

**Comment by UnamSanctam** [comment]
Yes you can run it and see if it uses any CPU, don't forget to disable "Stealth" for your test build since otherwise it will pause.

**Comment by Navajaa** [comment]
Ill try that out. Thanks for the quick response!

**Comment by Navajaa** [comment]
It seems to be working but is there an easy way to check if monero is actually being mined?

**Comment by Navajaa** [comment]
Im not 100% sure if I configured the pool and password and stuff correctly

**Comment by UnamSanctam** [comment]
If it's using CPU then it has successfully connected to the pool and is mining, otherwise no CPU could be used. You can go to the pool and enter your wallet address and it should say if you're mining, though it can take some time to appear. You can laso run this [MinerCheck3.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/7274231/MinerCheck3.zip) program and post a screenshot of what it says here and I'll check if everything is correct, though you should probably censor the wallet address. 
.
