### ISSUE TITLE
nanopool

### ISSUE THREAD

**Issue by bashicq** [UnamSanctam/SilentXMRMiner#458]
First of all, I want to say that somewhere here in the threads I read that nanopool allows you to have an unlimited number of workers.
At first, there was one name for everyone, and on the first day on the nanopool I got 36kh, this is the maximum amount. After everything sank to 20-25 kh, I thought that the workers themselves left, for example, because of the antivirus. So, after a while, I changed the name of the worker from one to {computername} and kh increased at the maximum point to 50. Do you think this is an accident?

And one more thing: the workers have very similar names
They start with СDESKTOP plus random three letters.

**Comment by UnamSanctam** [comment]
Hmm, I think it's just a coincidence, I have seen people with 20 000 workers but of course we can never really know unless we do a longer testing period. 

The computer names looking like that is normal since that is the standard Windows computer naming scheme. It's C (my miner adds it in case the computer name is only non-alphanumeric characters) + The desktop name (The standard Windows desktop name is half random like DESKTOP-U7RY5G).

**Comment by bashicq** [comment]
And I also forgot to say, before changing the name to {computername}, I transferred them to ssl work, and at the same time kh was also rising, and looking at these two elevations, we can assume that this is a law, not an accident.

**Comment by bashicq** [comment]
I already thought that I had done something wrong and instead of the computer name I got a random name =)
By the way, is it possible to do this:
xmrwallet.myword{computername}/password?

**Comment by UnamSanctam** [comment]
> And I also forgot to say, before changing the name to {computername}, I transferred them to ssl work, and at the same time kh was also rising, and looking at these two elevations, we can assume that this is a law, not an accident.

Hmm maybe, though SSL can technically increase the miners as well if something is blocking them since SSL is an encrypted connection. Does that hashrate include old miners and are you building and spreading one from the new version? Since then that could also be something since the new miner is a lot more undetectable and harder to remove.



> I already thought that I had done something wrong and instead of the computer name I got a random name =) By the way, is it possible to do this: xmrwallet.myword{computername}/password?

It will use a random name if it's unable to get the computer name or something else to make sure that the miner will still work (since some pool reject empty worker names). And yes you can do that with the worker name, though keep in mind that some pools have limits to worker names such as between 10-20 characters maximum, it depends on the pool.

**Comment by bashicq** [comment]
> Does that hashrate include old miners and are you building and spreading one from the new version

There are also miners there whose remote configuration was of the type ini and not json. There are miners of many versions, including new ones.

**Comment by UnamSanctam** [comment]
Yeah ok, I have seen a lot more miners not being removed now with the newest version since it's a lot more undetectable and harder to remove which is why I thought that it could have been a factor.

**Comment by bashicq** [comment]
![image_2021-10-05_18-35-10](https://user-images.githubusercontent.com/88036194/136056363-1dd047d5-1059-4d4d-b5ef-ebc009c9b3a9.png)
For clarity. Here, at the first peak, the transfer to ssl, at the second, the addition of {computername}.

**Comment by UnamSanctam** [comment]
Hmm, interesting, though it's hard to know the exact cause of it. You could experiment with the worker name for a longer period of time (using SSL is almost always better). Also make sure that you don't have "keepalive" enabled for nanopool since it doesn't seem to work there.

**Comment by bashicq** [comment]
> Also make sure that you don't have "keepalive" enabled for nanopool since it doesn't seem to work there.

It is disabled =)

By the way, remind me how remote access of the ini type was configured, {%computername%} right?

**Comment by UnamSanctam** [comment]
Yes exactly, it got changed in the newer versions since it conflicted with batch.

**Comment by bashicq** [comment]
Got it, thanks.
If anything happens, I will keep you up to date.
