### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ghost** [UnamSanctam/SilentXMRMiner#461]
(not an issue)

Do you think you the have time to make a tutorial for the usage? I think it would it make ten times easier to set up if you did.

**Comment by UnamSanctam** [comment]
Well the wiki has information on all the options https://github.com/UnamSanctam/SilentXMRMiner/wiki, I might make some sort of tutorial in the future when I release the next unified miner (this miner still works fine, the new one will just be a unified miner of the XMR and ETH miners) since otherwise I'm going to have to maintain two tutorials (since I have two miners).
