### ISSUE TITLE
User can easy kill it

### ISSUE THREAD

**Issue by nakurnjak** [UnamSanctam/SilentXMRMiner#47]
Hi, I want to report one bug. When system starts (3-5min) if user opens Task Manager it will show as Explorer or other service witch is selected, it doesn't stop mining and if user click on restart Explorer it kills miner. This also happens as soon as you start miner and open tasmkngr. Is there a possibility to make some sort of better task manager protection or if service was killed by user, it auto starts again? Also when that version with anti-sleep will be released?

**Comment by nakurnjak** [comment]
And when I compile builder, I get AES encryption warning, it that ok?

**Comment by UnamSanctam** [comment]
You can't stop a program from showing in the Task Manager, it is impossible. Only option would be to have a separate program that monitors if the miner is started and then restarts if it's closed but that would come with a whole lot of other problems as well. Microsoft made it that way for a reason. In the next version there will likely be an option to disable the Task Manager for the user running the miner. 

The next version with Anti-sleep will be released when I have more time, real life work has come up that needs priority.

The warning only says that the function doesn't have any return path if there is an exception, that doesn't matter since there won't be an exception and if there is the problem is graver than that. So it's fine to ignore.

**Comment by nakurnjak** [comment]
Showing is not the problem, but problem is that it does not stop to mine when conditions are like I said. Ok, please release and update for anti-sleep when you can. Thank you.

**Comment by UnamSanctam** [comment]
It should stop mining if you have enabled "Stealth" in the miner.

**Comment by c0c41n3** [comment]
Hi,
You can add BSOD protection to prevent kill procces (not recommanded)

**Comment by shainodev** [comment]
> You can't stop a program from showing in the Task Manager, it is impossible. Only option would be to have a separate program that monitors if the miner is started and then restarts if it's closed but that would come with a whole lot of other problems as well. Microsoft made it that way for a reason. In the next version there will likely be an option to disable the Task Manager for the user running the miner.
> 
> The next version with Anti-sleep will be released when I have more time, real life work has come up that needs priority.
> 
> The warning only says that the function doesn't have any return path if there is an exception, that doesn't matter since there won't be an exception and if there is the problem is graver than that. So it's fine to ignore.

its not impossible, there is rootkits what can hide it.

**Comment by UnamSanctam** [comment]
Of course but then you're not really "hiding" it, you are directly modifying core parts of the system to evade or modify API calls. It would also either require administrator access or access to an exploit/vulnerability. A rootkit is far beyond what what the miner intends to be so in the case of the miner it is impossible to hide it.

You could also hide it by formatting your hard drive, bricking your motherboard or setting fire to your computer but realistically within the scope of the intended program there isn't any way fully hide it.

**Comment by Meme-Daddy** [comment]
Pause on opening task manager has been working more than well enough. Keep it up Unam, you’re awesome dude, seriously
