### ISSUE TITLE
cannot disable normal miner

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentXMRMiner#48]
is there no way to put normal cpu as 0% for it to only enable in idle?

**Comment by shainodev** [comment]
suggestion: If user deletes the startup entry, the miner will write a new startup entry immediately.

**Comment by UnamSanctam** [comment]
Well... I have never tried putting it at 0% so I'm not sure, the Idle CPU 0% is custom made by me to pause the miner instead of putting it at 0% so I'm not sure how it would work normally. I guess you could download the miner and add 0% to the Combobox and compile it yourself, I can try to add something custom for it in the next version.

It's not really possible to add a new registry entry while the miner is running since the program that does it has already closed down and only the miner is running.

**Comment by shainodev** [comment]
can a watchdog really increase the detection rate?

**Comment by UnamSanctam** [comment]
Of course, it would also have to be injected and then stay and poll Windows APIs to check if everything is running. I still have problems with the KillLastProc() function since it polls the Windows WMI API to check if any miners are running, I even removed the code at one point since I couldn't find a way to stop AVs from detecting it.

I might make some kind of program for it in the future but I would have to find some solutions for some problems it could cause.

**Comment by shainodev** [comment]
ight, last thing is the userinit startup way is it possible?

**Comment by UnamSanctam** [comment]
I will try to add that but since it isn't really supposed to be used there isn't really much information about the required permissions and compatibility between versions so I'll have to do tests.

**Comment by shainodev** [comment]
ayo i use minergate for mining and all of my unconfirmed balance has just reset completely 0??? why??

**Comment by UnamSanctam** [comment]
I'm not sure, I've never used MinerGate so I'm not very familiar with how it works.

**Comment by shainodev** [comment]
what have u used?

**Comment by UnamSanctam** [comment]
Only nanopool since most other sites ban you if you have over 100 miners (they believe you have a botnet).

**Comment by shainodev** [comment]
does nanopool log like, ips or such?

**Comment by UnamSanctam** [comment]
Not so far as I know.

**Comment by shainodev** [comment]
also can pool.supportxmr.com ban me?

**Comment by UnamSanctam** [comment]
Yes if you search online you can find see that the owner bans people if they think it's a botnet or malicious mining.

**Comment by shainodev** [comment]
aww ill use nanopool then

**Comment by shainodev** [comment]
wait sorry that im annoying but is there a way to prevent from him banning me? or he will just ban my worker or workers. if there isnt a way to prevent it, can you help me with nanopool? what do i use in xmr builder than i normally do

**Comment by UnamSanctam** [comment]
The supportxmr admin will ban your wallet address so that you can't mine or withdraw any XMR, the workaround is to use xmrig-proxy and mine to that and then the proxy connects to supportxmr but it's quite advanced to set up and requires you to have your own server. 

To mine to nanopool just use any pool address here: https://help.nanopool.org/article/59-pool-information for example xmr-eu1.nanopool.org:14433 and enable SSL if you use 14433 and don't enable it if you use 14444 (SSL is recommended). Then just enter your wallet address and leave the password blank. The default minimum XMR payout is 1 XMR but can be changed to 0.1 XMR.

**Comment by shainodev** [comment]
whats the difference between 14433 and 14444

**Comment by UnamSanctam** [comment]
14433 is the SSL port and more stable and 14444 is stratum port. If you use 14433 then enable SSL/TLS otherwise don't enable it.

**Comment by shainodev** [comment]
thanks you are really heplful, i will try to find more bugs and contact u, ight cya.

**Comment by shainodev** [comment]
lmao, im back just to tell u i did a scan with my windows defender and it detected my .txt file as a virus lol, and it contains "mygmailxd@gmail.com
xmr.pool.minergate.com:45700
x", just thought this would help u

**Comment by UnamSanctam** [comment]
Yeah they detect strings like "xmr.pool.minergate.com" which is annoying. In the latest release I encrypted all the strings to try and circumvent it, but good to know.

**Comment by shainodev** [comment]
i might not be right, but im sure that if u use names in Public Shared Sub's like Install, Payload, etc. like windows defender does it detects strings or may as well the Registry.CurrentUser.CreateSubKey("Software\Microsoft\....

**Comment by UnamSanctam** [comment]
Yeah which is why using a .NET Obfuscator is really good since it scrambles all the names.

**Comment by shainodev** [comment]
which one, everything i use is saying its already obfuscated

**Comment by UnamSanctam** [comment]
Downloadhttps://github.com/mkaring/ConfuserEx and then load this project https://anonfiles.com/H3wff7Hfp3/SilentXMRMiner_crproj and then add your file by dragging it in on the first tab then pressing protect in the Protect tab you will get an obfuscated file inside the Confused folder.

**Comment by shainodev** [comment]
thanks

**Comment by shainodev** [comment]
Ayo, does AntiVM cause issues, raise detections or anything? If no, could u add it? if u are gonna add it also u could consider Anti Sandboxie, Anti Debugger (checks if its run in a debugger not if a debugger is open), etc?

**Comment by UnamSanctam** [comment]
The obfuscator I sent before already includes most of that, but otherwise it's not the easiest to include, especially in VB .NET but might add some sort of custom solution if I can figure out one.
