### ISSUE TITLE
Quick quesiton 

### ISSUE THREAD

**Issue by muggs88** [UnamSanctam/SilentXMRMiner#490]
I was wondering. If someone runs the miner with admin privilege's, and then runs it again without admin privilege's, will the version of the miner when the person accepts admin privilege's be active or would the version of the miner without admin privilege's be active.

**Comment by UnamSanctam** [comment]
If you compile it with "Run as Administrator" enabled then you can only start it as administrator and not a normal user (that's how Windows works). But if you mean a miner without "Run as Administrator" being run as an administrator manually)and then as a normal user (in that exact order) then it would most likely start twice since it's impossible for the normal users miner to read the administrator processes to see if it's already running. But the miner would still only be installed once so after restart it would only start one anyways.

**Comment by muggs88** [comment]
What if I compile it with run as administrator. They start it as administrator and it runs. And then they run it again but decline administrator. Would the miner still be running or because they ran it again and declined administrator would it overwrite it and stop the miner. If that makes sense.

**Comment by UnamSanctam** [comment]
If you decline running it as administrator then it won't run, that's how Windows works.

**Comment by muggs88** [comment]
Even if after running it with administrator first.

**Comment by UnamSanctam** [comment]
If you decline the administrator rights request then Windows will not start the file, the administrator rights request is done by Windows and not the miner itself.

**Comment by muggs88** [comment]
Oh ok I was confused. Also, I am excited for the unified miner, how far have you gotten?

**Comment by UnamSanctam** [comment]
Both the ETH miner and XMR miners are basically done, I just have the finish the quality of life stuff in the panel (and have to fix my test servers networking since it broke completely today). Then I just have to finish the multi-language support in the builder (already finished in the panel).

**Comment by muggs88** [comment]
I am very excited keep up the good work!!!
