### ISSUE TITLE
suspiciously long parameter

### ISSUE THREAD

**Issue by Spectrum735** [UnamSanctam/SilentXMRMiner#511]
hi, if I activate the command line column in taskmgr, you will see a very long parameter in the infected process. This raises some suspicion among advanced users. Is it possible to make this parameter shorter and not attract attention? What if we put this parameter directly into the code before the build, but call it with another shorter parameter? Any suggestions?

![изображение](https://user-images.githubusercontent.com/56220293/147508596-7978f630-ac9f-4ae9-a553-b0679fa70d47.png)

**Comment by UnamSanctam** [comment]
No you cannot get rid of it or shorten it since the miner needs to know what settings to use. The miner binary itself is not compiled inside the builder (since that would be nearly impossible) so the injector has to tell the pre-compiled miner binary what settings it should use. In my new miner: https://github.com/UnamSanctam/SilentCryptoMiner the command line string is encrypted though which makes it harder to discern its purpose.

**Comment by Spectrum735** [comment]
Ok, thanks
