### ISSUE TITLE
modified xmrig

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentXMRMiner#52]
Hello, I'm not sure if you have modified the XMRIG to get the idle and max CPU stuff but I have found this modified XMRIG it doesn't only mine XMR but it does benchmark on each execution of miner and mines the most profitable coin then converts it to XMR in your wallet, CPU dependent: https://github.com/MoneroOcean/xmrig. Please have a look into this and consider adding it.

**Comment by YouUnderscoreded** [comment]
You can customize this project to your own liking since it is open source. Have visual studio 2017 or higher, I am using Visual Studio 2019. Download the binaries for xmrig from MoneroOcean, open the source code for SilentXMRMiner, in resources replace xmrig.zip with a zip file which has xmrig.exe that you downloaded inside it, and also add the DLL file that comes with xmrig to resources, then build it.

**Comment by YouUnderscoreded** [comment]
I tried to implement this myself but CPU max load tends to break after a point and go to as high as it can. I believe the author of SilentXMRMiner did modify his XMRIG. It would be really helpful to implement this or release changed source code so we can.
