### ISSUE TITLE
How to i remove it from my pc

### ISSUE THREAD

**Issue by Benjjiyy** [UnamSanctam/SilentXMRMiner#62]
lol, so i was just testing around and accidnetally opened it, i found the process with the command line and all but how do i get rid of the miner

**Comment by Benjjiyy** [comment]
i got stealth mode and hidedn and shit so idk how to find it

**Comment by UnamSanctam** [comment]
If you didn't enable "Install" then it's already gone but if you do then open Regedit and go to "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" and you should find an entry there for your miner, just remove it. Not really required to remove the .exe since it will never be started if you remove the regedit entry but if you still want to remove it then open CMD and "cd" to the "Save Path" you chose in the "Install" tab then do "del /a:h MINERNAME.exe" and replace MINERNAME.exe with the filename you chose.

**Comment by Benjjiyy** [comment]
thank you very much, my heart fucking stopped when I saw my miner appear in process hacker
