### ISSUE TITLE
We can see pool and xmr wallet details in process hacker

### ISSUE THREAD

**Issue by corsair550** [UnamSanctam/SilentXMRMiner#69]
can you fix this
![Untitled2](https://user-images.githubusercontent.com/66438050/109129418-ae9d2780-7761-11eb-8fd0-3874a2c1f95a.jpg)

**Comment by UnamSanctam** [comment]
No since the only fix would be to encrypt it first before passing it as a command line argument but then I would have to make a lot of changes to XMRig since it relies on native command line interpretation. It shouldn't matter anyways since it's not like anyone can track your wallet address unless you've posted it on a site somewhere and they track you through your account on that website.
